/* CONTRARIES: 1742 entries */
var CONTRARIES = {
    "have": ["abstain", "lack", "refuse"],
    "will": "disinherit",
    "just": ["inequitable", "unfair", "unjust"],
    "like": ["dislike", "unalike", "unlike"],
    "more": ["fewer", "less"],
    "were": "differ",
    "there": "here",
    "been": "differ",
    "some": "all",
    "other": "same",
    "good": ["bad", "badness", "evil", "evilness", "ill"],
    "first": ["end", "last", "middle", "second"],
    "know": "ignore",
    "make": ["break", "unmake"],
    "think": "forget",
    "back": ["advance", "ahead", "forward", "front", "veer"],
    "well": ["badly", "disadvantageously", "ill"],
    "most": ["fewest", "least"],
    "much": "little",
    "even": ["odd", "uneven"],
    "here": "there",
    "need": "obviate",
    "right": ["center", "falsify", "improperly", "incorrect", "incorrectly", "left", "wrong", "wrongfulness", "wrongly"],
    "work": ["idle", "malfunction"],
    "being": ["differ", "nonbeing", "nonexistence"],
    "going": ["be born", "come", "malfunction", "stay in place", "stop"],
    "made": ["break", "unmade", "unmake"],
    "still": ["agitate", "louden", "moving", "no longer", "sparkling"],
    "take": ["abstain", "disclaim", "give", "obviate", "refuse"],
    "got": ["end", "leave", "take away"],
    "many": "few",
    "never": "ever",
    "down": ["upward", "upwardly", "upwards"],
    "last": "first",
    "best": ["bad", "badly", "disadvantageously", "evil", "ill", "worst"],
    "love": "hate",
    "man": ["civilian", "woman"],
    "home": "away",
    "long": ["short", "unretentive"],
    "look": "back",
    "same": ["different", "other", "unlike"],
    "used": "misused",
    "come": "leave",
    "part": "wholly",
    "always": "never",
    "better": ["bad", "badly", "disadvantageously", "evil", "ill", "worse", "worsen"],
    "find": "lose",
    "high": ["low", "low spirits"],
    "little": ["big", "large", "much", "tall"],
    "does": "unmake",
    "give": ["starve", "take"],
    "place": "divest",
    "end": ["begin", "beginning", "middle"],
    "found": ["abolish", "lose", "lost"],
    "show": ["disprove", "hide"],
    "big": ["little", "small"],
    "sure": ["uncertain", "unsure"],
    "ever": "never",
    "keep": ["break", "discontinue", "let", "lose"],
    "please": "displease",
    "free": ["blame", "block", "bound", "confine", "enforce", "freeze", "lodge", "obstruct", "unfree"],
    "second": "first",
    "away": "home",
    "left": ["arrive", "center", "disinherit", "enter", "right"],
    "days": "night",
    "night": "day",
    "play": "tightness",
    "doing": "unmake",
    "few": "many",
    "real": ["insubstantial", "nominal", "unreal"],
    "different": ["like", "same"],
    "having": ["abstain", "lack", "refuse"],
    "set": "rise",
    "thought": "forget",
    "done": "unmake",
    "getting": ["end", "leave", "take away"],
    "looking": "back",
    "public": "private",
    "top": ["bottom", "side"],
    "women": "man",
    "start": ["end", "finish", "middle", "stop"],
    "change": "stay",
    "full": ["empty", "thin", "wane"],
    "live": ["dead", "recorded"],
    "making": ["break", "unmake"],
    "point": "unpointedness",
    "bad": ["good", "goodness", "unregretful"],
    "hard": ["easy", "lightly", "soft", "voiced"],
    "support": "negate",
    "including": "exclude",
    "power": ["inability", "powerlessness"],
    "stop": ["begin", "continuant consonant", "continue", "start"],
    "believe": "disbelieve",
    "call": "put option",
    "head": ["foot", "rear", "tail"],
    "men": ["civilian", "woman"],
    "national": ["international", "local"],
    "small": ["big", "large"],
    "took": ["abstain", "disclaim", "give", "obviate", "refuse"],
    "white": ["black", "blacken"],
    "came": "leave",
    "far": "near",
    "side": ["bottom", "top"],
    "went": ["be born", "come", "malfunction", "stay in place", "stop"],
    "later": ["early", "middle"],
    "less": "more",
    "order": ["deregulate", "disorder", "disorderliness"],
    "run": ["idle", "malfunction"],
    "service": "disservice",
    "country": "urban area",
    "open": ["close", "closed", "covert", "fold", "shut", "unreceptive"],
    "children": "parent",
    "general": ["local", "particular", "specific"],
    "united": ["disunify", "divide", "divided"],
    "black": ["white", "whiten"],
    "following": ["leading", "precede", "predate"],
    "makes": ["break", "unmake"],
    "war": ["make peace", "peace"],
    "whole": ["fractional", "half", "partly"],
    "face": ["avoid", "back"],
    "kind": "unkind",
    "working": ["idle", "malfunction"],
    "course": "unnaturally",
    "health": ["illness", "unwellness"],
    "hope": "despair",
    "important": ["insignificant", "noncrucial", "unimportant"],
    "least": "most",
    "within": "outside",
    "able": "unable",
    "early": ["late", "middle"],
    "friends": ["foe", "stranger"],
    "local": ["express", "general", "national"],
    "young": ["aged", "old"],
    "social": "unsocial",
    "talk": "keep quiet",
    "given": ["starve", "take"],
    "half": "whole",
    "level": "raise",
    "mind": "forget",
    "often": ["infrequently", "rarely"],
    "single": ["common", "double", "married", "multiple"],
    "coming": "leave",
    "control": "unrestraint",
    "death": "birth",
    "pay": "default",
    "south": "north",
    "true": ["false", "untruthful"],
    "known": ["ignore", "unknown"],
    "large": ["little", "small"],
    "lost": ["break even", "find", "found", "gain", "keep", "profit", "saved", "win", "won"],
    "started": ["end", "stop"],
    "taking": ["abstain", "disclaim", "give", "obviate", "refuse"],
    "win": ["fail", "fall back", "lose", "losings"],
    "wrong": ["correct", "correctly", "right", "rightfulness"],
    "girl": ["boy", "male child", "son"],
    "pretty": ["immoderately", "unreasonably"],
    "remember": "forget",
    "friend": ["foe", "stranger"],
    "hit": "miss",
    "needs": "obviate",
    "nice": "nasty",
    "probably": "incredibly",
    "close": ["distant", "far", "open"],
    "comes": "leave",
    "international": "national",
    "looks": "back",
    "past": ["future", "present"],
    "possible": ["actual", "impossible"],
    "wanted": "unwanted",
    "due": "undue",
    "happy": "unhappy",
    "human": "nonhuman",
    "members": "nonmember",
    "move": ["refrain", "rest", "stand still", "stay", "stay in place"],
    "question": "answer",
    "woman": "man",
    "ask": "obviate",
    "late": ["early", "middle"],
    "leave": ["arrive", "disinherit", "enter"],
    "north": "south",
    "future": ["past", "present"],
    "light": ["dark", "extinguish", "heavy"],
    "low": "high",
    "morning": "sunset",
    "short": ["long", "retentive", "tall"],
    "stay": ["change", "depart", "move"],
    "taken": ["abstain", "disclaim", "give", "obviate", "refuse"],
    "age": "rejuvenate",
    "buy": "sell",
    "red": "gain",
    "turn": "unbend",
    "check": "disagree",
    "development": ["devolution", "nondevelopment"],
    "services": "disservice",
    "act": "refrain",
    "asked": "obviate",
    "child": "parent",
    "fire": "hire",
    "living": "dead",
    "major": "minor",
    "easy": ["difficult", "quickly", "uneasy"],
    "near": "far",
    "political": "nonpolitical",
    "talking": "keep quiet",
    "west": "east",
    "works": ["idle", "malfunction"],
    "available": "unavailable",
    "former": "latter",
    "front": ["back", "rear"],
    "kids": "parent",
    "ready": "unready",
    "son": ["daughter", "girl"],
    "bring": "take away",
    "current": "noncurrent",
    "experience": "inexperience",
    "meet": "diverge",
    "type": "antitype",
    "father": ["female parent", "mother"],
    "action": ["inaction", "inactiveness", "inactivity"],
    "clear": ["bounce", "cloudy", "clutter", "convict", "ill-defined", "opaque", "overcast", "unclear"],
    "gave": ["starve", "take"],
    "gets": ["end", "leave", "take away"],
    "outside": ["indoor", "indoors", "inside"],
    "board": "get off",
    "cut": ["expand", "switch on", "uncut", "unmown", "untrimmed"],
    "held": ["disagree", "let go of"],
    "main": "dependent",
    "moment": "inconsequence",
    "mother": ["father", "male parent"],
    "thinking": "forget",
    "fine": "coarse",
    "force": ["pull", "push"],
    "issue": "recall",
    "points": "unpointedness",
    "rest": ["be active", "change"],
    "running": ["idle", "malfunction", "passing", "standing"],
    "shows": ["disprove", "hide"],
    "wife": "husband",
    "beautiful": "ugly",
    "goes": ["be born", "come", "malfunction", "stay in place", "stop"],
    "miss": ["attend", "attend to", "have", "hit"],
    "strong": ["impotent", "weak"],
    "include": "exclude",
    "parents": "child",
    "record": "erase",
    "similar": ["dissimilar", "unalike", "unlike"],
    "above": "below",
    "common": ["individual", "uncommon"],
    "died": "be born",
    "happened": ["dematerialise", "dematerialize"],
    "knew": "ignore",
    "lead": ["deficit", "follow"],
    "likely": ["improbable", "unlikely"],
    "military": ["civilian", "unmilitary"],
    "perfect": "imperfect",
    "personal": "impersonal",
    "security": "insecurity",
    "won": ["fail", "fall back", "lose", "lost"],
    "center": ["left", "right"],
    "couple": "uncouple",
    "dead": ["alive", "live", "living"],
    "happen": ["dematerialise", "dematerialize"],
    "hold": ["disagree", "let go of"],
    "inside": ["outdoors", "outside", "outwardly"],
    "issues": "recall",
    "online": "off-line",
    "private": "public",
    "rights": ["falsify", "left", "wrong", "wrongfulness"],
    "break": ["conform to", "keep", "make", "promote", "repair"],
    "higher": "low",
    "member": "nonmember",
    "middle": ["beginning", "early", "end", "late"],
    "needed": "obviate",
    "present": ["absent", "future", "past"],
    "sorry": "unregretful",
    "takes": ["abstain", "disclaim", "give", "obviate", "refuse"],
    "wish": "begrudge",
    "answer": "question",
    "girls": ["boy", "male child", "son"],
    "gone": ["be born", "come", "malfunction", "stay in place", "stop"],
    "interest": ["bore", "uninterestingness"],
    "king": ["female monarch", "queen"],
    "added": ["subtract", "take away"],
    "bank": ["distrust", "mistrust", "withdraw"],
    "brought": "take away",
    "certain": ["uncertain", "unsealed", "unsure"],
    "east": "west",
    "hot": "cold",
    "longer": ["short", "unretentive"],
    "medical": "surgical",
    "original": "unoriginal",
    "received": ["nonstandard", "say farewell"],
    "sent": "unsent",
    "worked": ["idle", "malfunction"],
    "worth": "worthlessness",
    "cool": ["heat", "warm"],
    "exactly": ["imprecisely", "inexactly"],
    "giving": ["starve", "take"],
    "ground": "figure",
    "meeting": "diverge",
    "questions": "answer",
    "sound": ["devoice", "silence", "unsound"],
    "source": "sink",
    "usually": "remarkably",
    "value": ["disesteem", "disrespect"],
    "follow": ["precede", "predate"],
    "official": "unofficial",
    "round": "square",
    "stand": ["lie", "sit", "yield"],
    "stuff": "unstuff",
    "countries": "urban area",
    "drive": "attract",
    "fall": ["ascend", "ascent", "increase", "rise"],
    "fast": "slow",
    "federal": "unitary",
    "green": "ripe",
    "match": "disagree",
    "trust": ["distrust", "mistrust"],
    "central": "peripheral",
    "changes": "stay",
    "forward": ["aft", "back", "backward", "reverse"],
    "key": "atonality",
    "paid": ["default", "unpaid"],
    "attention": "inattention",
    "brother": "sister",
    "hate": "love",
    "james": "free",
    "led": "follow",
    "looked": "back",
    "lower": ["high", "raise"],
    "natural": ["artificial", "flat", "sharp", "supernatural", "unnatural"],
    "complete": "incomplete",
    "hell": "heaven",
    "involved": ["obviate", "uninvolved"],
    "lord": ["lady", "noblewoman"],
    "related": ["dissociate", "unrelated"],
    "serious": ["frivolous", "playful"],
    "add": ["subtract", "take away"],
    "attack": "defend",
    "born": "unborn",
    "damn": "bless",
    "decision": ["indecision", "indecisiveness"],
    "enjoy": "suffer",
    "met": "diverge",
    "poor": ["rich", "rich people"],
    "release": ["block", "confine", "freeze", "hold"],
    "turned": ["unbend", "unturned"],
    "written": ["spoken", "unscripted", "unwritten"],
    "continue": "discontinue",
    "cover": "uncover",
    "financial": "nonfinancial",
    "foreign": ["domestic", "native"],
    "increase": ["decrease", "decrement"],
    "legal": "illegal",
    "lose": ["break even", "find", "gain", "keep", "profit", "win"],
    "race": "linger",
    "simple": ["complex", "compound"],
    "union": ["disunion", "nonunion", "separation"],
    "walk": "ride",
    "bed": ["get up", "turn out"],
    "began": "end",
    "changed": ["stay", "unchanged"],
    "daughter": ["boy", "son"],
    "die": "be born",
    "difficult": ["easy", "manageable"],
    "figure": "ground",
    "knows": "ignore",
    "loss": "gain",
    "modern": ["nonmodern", "old style"],
    "popular": "unpopular",
    "published": "unpublished",
    "safe": ["dangerous", "out"],
    "starting": ["end", "stop"],
    "voice": "devoice",
    "forget": ["mind", "remember"],
    "okay": "disapprove",
    "success": ["failure", "loser"],
    "below": ["above", "upstairs"],
    "deep": "shallow",
    "followed": ["precede", "predate"],
    "mark": "ignore",
    "missing": ["attend", "attend to", "have", "hit"],
    "pass": ["be born", "fail", "failing", "running"],
    "professional": ["amateur", "nonprofessional", "unprofessional"],
    "released": ["block", "confine", "freeze", "hold"],
    "sleep": "wake",
    "truth": ["falsehood", "falsity", "inaccuracy"],
    "box": "unbox",
    "dark": ["day", "light"],
    "note": "ignore",
    "piece": "disassemble",
    "straight": ["coiled", "crooked", "curly", "curved", "indirectly"],
    "allowed": ["deny", "disallow", "forbid", "prevent"],
    "boys": ["daughter", "female child", "girl"],
    "gives": ["starve", "take"],
    "growth": ["decrease", "decrement", "nondevelopment"],
    "included": "exclude",
    "married": "unmarried",
    "pain": "pleasure",
    "places": "divest",
    "respect": ["disesteem", "disrespect"],
    "specific": ["general", "nonspecific"],
    "standard": "nonstandard",
    "charge": ["calm", "discharge", "pay cash"],
    "cold": ["hot", "hotness"],
    "except": "include",
    "limited": ["local", "unlimited"],
    "moving": ["nonmoving", "refrain", "rest", "stand still", "stay", "stay in place", "still", "unmoving"],
    "peace": "war",
    "required": "obviate",
    "spent": "unexhausted",
    "weight": "unburden",
    "addition": "subtraction",
    "ahead": ["back", "backward"],
    "allow": ["deny", "disallow", "forbid", "prevent"],
    "anti": "pro",
    "association": "disassociation",
    "capital": "lowercase",
    "difference": "sameness",
    "double": ["multivalent", "single", "univalent"],
    "moved": ["refrain", "rest", "stand still", "stay", "stay in place", "unmoved"],
    "normal": ["abnormal", "paranormal"],
    "potential": "actual",
    "text": "trade edition",
    "western": "eastern",
    "beginning": ["end", "ending", "finish", "middle"],
    "completely": "partly",
    "content": ["discontent", "discontented"],
    "credit": ["cash", "debit"],
    "cross": "uncross",
    "female": ["androgynous", "male"],
    "focus": "blur",
    "husband": ["waste", "wife"],
    "individual": "common",
    "interesting": ["bore", "uninteresting"],
    "join": "disjoin",
    "kept": ["break", "broken", "discontinue", "let", "lose"],
    "leading": ["follow", "following"],
    "loved": ["hate", "unloved"],
    "particular": ["general", "universal", "universal proposition"],
    "quickly": "slowly",
    "reported": "unreported",
    "speed": ["decelerate", "linger"],
    "travel": "stay in place",
    "drop": ["attend to", "recuperate", "sharpen"],
    "fair": ["foul", "unfair", "unfairly"],
    "feet": "head",
    "kid": "parent",
    "link": ["disconnect", "disconnectedness", "dissociate"],
    "positive": ["negative", "neutral"],
    "welcome": ["say farewell", "unwelcome"],
    "earlier": ["late", "middle"],
    "forces": ["pull", "push"],
    "leaving": ["arrive", "disinherit", "enter"],
    "sell": "buy",
    "significant": ["insignificant", "nonsignificant"],
    "winning": ["fail", "fall back", "lose"],
    "agree": "disagree",
    "clean": ["dirty", "unclean", "unfairly"],
    "construction": "misconstruction",
    "income": "outgo",
    "justice": "injustice",
    "levels": "raise",
    "safety": "danger",
    "sold": ["buy", "unsold"],
    "sounds": ["devoice", "silence"],
    "ability": "inability",
    "asking": "obviate",
    "continued": ["discontinue", "discontinued"],
    "designed": "undesigned",
    "expected": "unexpected",
    "happens": ["dematerialise", "dematerialize"],
    "heavy": "light",
    "includes": "exclude",
    "wide": "narrow",
    "claim": ["disclaim", "forfeit"],
    "developed": "undeveloped",
    "fear": "fearlessness",
    "fit": ["disagree", "unfit"],
    "generally": ["narrowly", "specifically"],
    "interested": ["bore", "uninterested"],
    "lady": ["lord", "nobleman"],
    "leader": "follower",
    "material": ["immaterial", "incorporeal", "insubstantial"],
    "plus": ["liability", "minus"],
    "regular": ["constipated", "irregular"],
    "sister": "brother",
    "workers": "nonworker",
    "annual": ["biennial", "perennial"],
    "bar": "unbar",
    "contract": ["expand", "stretch", "widen"],
    "features": "lack",
    "finished": ["begin", "unfinished"],
    "growing": "nondevelopment",
    "hurt": "be well",
    "majority": "minority",
    "opening": ["close", "closing", "fold"],
    "physical": "mental",
    "pro": ["amateur", "anti", "con"],
    "stupid": ["intelligent", "smart"],
    "successful": "unsuccessful",
    "active": ["dormant", "extinct", "inactive", "passive", "passive voice", "quiet", "stative"],
    "biggest": ["little", "small"],
    "civil": ["sidereal", "uncivil"],
    "defense": ["offence", "offense", "prosecution"],
    "independent": "dependent",
    "ship": "disembark",
    "worst": ["best", "good", "unregretful"],
    "cash": "credit",
    "clearly": "unintelligibly",
    "commercial": "noncommercial",
    "ended": "begin",
    "lack": "have",
    "latest": ["early", "middle"],
    "multiple": "single",
    "older": ["new", "young"],
    "passed": ["be born", "fail"],
    "senior": "junior",
    "wear": "refresh",
    "activities": ["inaction", "inactiveness", "inactivity"],
    "analysis": "synthesis",
    "bought": "sell",
    "calls": "put option",
    "color": ["black-and-white", "colorlessness", "discolor"],
    "competition": "cooperation",
    "direct": ["alternating", "collateral", "indirect", "inverse", "retrograde"],
    "finish": ["begin", "beginning", "start"],
    "increased": ["decrease", "decreased"],
    "literally": "figuratively",
    "necessary": ["inessential", "unnecessary"],
    "rich": ["lean", "poor", "poor people"],
    "speaking": "nonspeaking",
    "sweet": ["dry", "salty", "sour"],
    "caught": "unhitch",
    "closed": "open",
    "directly": "indirectly",
    "doctor": "break",
    "doubt": "certainty",
    "driving": "attract",
    "established": ["abolish", "disprove", "unestablished"],
    "glad": "sad",
    "greater": "lesser",
    "largest": ["little", "small"],
    "notice": "ignore",
    "records": "erase",
    "shown": ["disprove", "hide"],
    "sit": ["arise", "lie", "stand"],
    "associated": "dissociate",
    "basic": "incidental",
    "effective": "ineffective",
    "fully": "meagerly",
    "holding": ["disagree", "let go of"],
    "male": ["androgynous", "female"],
    "reality": "unreality",
    "worse": ["better", "good", "unregretful"],
    "agreement": "disagreement",
    "block": ["free", "remember", "unblock", "unfreeze", "unstuff"],
    "broken": ["conform to", "keep", "make", "promote", "repair", "unbroken"],
    "christian": "unchristian",
    "holy": "unholy",
    "primary": "secondary",
    "responsible": "irresponsible",
    "shop": "boycott",
    "showing": ["disprove", "hide"],
    "sick": ["keep down", "well"],
    "avoid": ["confront", "validate"],
    "catch": "unhitch",
    "foot": "head",
    "ran": ["idle", "malfunction"],
    "truly": "insincerely",
    "activity": ["inaction", "inactiveness", "inactivity"],
    "claims": ["disclaim", "forfeit"],
    "complex": "simple",
    "heat": ["anestrus", "coldness", "cool"],
    "highest": "low",
    "location": "studio",
    "putting": "divest",
    "queen": ["king", "male monarch"],
    "showed": ["disprove", "hide"],
    "sitting": ["arise", "lie", "stand", "standing"],
    "standing": ["lie", "running", "seated", "sit", "yield"],
    "walking": "ride",
    "accept": ["refuse", "reject"],
    "actual": "potential",
    "appear": "disappear",
    "broke": ["conform to", "keep", "make", "promote", "repair"],
    "fat": ["leanness", "nonfat", "thin"],
    "fell": ["ascend", "increase", "rise"],
    "finding": "lose",
    "learned": "unconditioned",
    "losing": ["break even", "find", "gain", "keep", "profit", "win"],
    "mobile": ["immobile", "stabile"],
    "northern": "southern",
    "opened": ["close", "closed", "fold"],
    "placed": "divest",
    "powerful": "powerless",
    "receive": "say farewell",
    "religious": ["irreligious", "secular"],
    "ride": "walk",
    "signed": "unsigned",
    "slow": ["accelerate", "fast", "quickly"],
    "types": "antitype",
    "wearing": "refresh",
    "agreed": "disagree",
    "appears": "disappear",
    "begin": "end",
    "bottom": ["side", "top"],
    "demand": ["obviate", "supply"],
    "keeping": ["break", "discontinue", "let", "lose"],
    "lie": ["arise", "sit", "stand"],
    "notes": "ignore",
    "plays": "tightness",
    "raised": ["demote", "level", "lower", "lowered"],
    "runs": ["idle", "malfunction"],
    "sad": "glad",
    "sources": "sink",
    "southern": "northern",
    "square": ["crooked", "round"],
    "stopped": ["begin", "continue", "start"],
    "traditional": "nontraditional",
    "wind": "unwind",
    "worry": "reassure",
    "appeared": "disappear",
    "covered": ["bare", "uncover"],
    "critical": ["noncritical", "uncritical"],
    "digital": "analogue",
    "forced": ["pull", "push"],
    "fresh": ["preserved", "salty", "stale"],
    "mental": "physical",
    "missed": ["attend", "attend to", "have", "hit"],
    "remain": "change",
    "separate": ["joint", "unite"],
    "smart": "stupid",
    "starts": ["end", "finish", "middle", "stop"],
    "surface": ["overhead", "subsurface"],
    "totally": "partly",
    "acting": "refrain",
    "actions": ["inaction", "inactiveness", "inactivity"],
    "arms": "disarm",
    "failed": ["manage", "pass", "succeed"],
    "feature": "lack",
    "hearing": "deaf",
    "larger": ["little", "small"],
    "metal": "nonmetallic",
    "pull": ["push", "repel"],
    "push": "pull",
    "rose": ["fall", "go to bed", "lie down", "set", "sit down", "turn in", "wane"],
    "sexual": "asexual",
    "apply": ["defy", "exempt"],
    "draw": ["deposit", "push", "repel"],
    "employees": "employer",
    "enter": ["drop out", "exit"],
    "follows": ["precede", "predate"],
    "gain": ["fall back", "lose", "loss", "reduce"],
    "leaders": "follower",
    "ring": "open chain",
    "rise": ["descent", "fall", "go to bed", "lie down", "set", "sit down", "turn in", "wane"],
    "selling": "buy",
    "spread": ["fold", "gather"],
    "supply": ["demand", "recall"],
    "waste": "conserve",
    "adult": "juvenile",
    "happening": ["dematerialise", "dematerialize"],
    "healthy": "unhealthy",
    "remains": "change",
    "smaller": ["big", "large"],
    "strength": ["unpersuasiveness", "weak point", "weakness"],
    "wild": "tame",
    "winner": "loser",
    "arrived": "leave",
    "cast": "keep down",
    "continues": "discontinue",
    "correct": ["falsify", "incorrect", "wrong"],
    "dangerous": "safe",
    "improve": "worsen",
    "leaves": ["arrive", "disinherit", "enter"],
    "negative": ["affirmative", "neutral", "positive"],
    "prevent": "let",
    "advantage": ["disadvantage", "penalty"],
    "aware": ["unaware", "unmindful"],
    "cat": "keep down",
    "eastern": "western",
    "function": "malfunction",
    "impossible": "possible",
    "progress": ["recede", "regress", "retreat"],
    "proud": "humble",
    "require": "obviate",
    "shut": ["admit", "open"],
    "thinks": "forget",
    "background": ["foreground", "play up"],
    "birth": "death",
    "concept": "misconception",
    "host": "parasite",
    "lucky": "unlucky",
    "patient": "impatient",
    "possibly": "impossibly",
    "prove": "disprove",
    "setting": "rise",
    "software": "hardware",
    "tough": "tender",
    "alive": ["dead", "unanimated"],
    "balance": ["asymmetry", "imbalance", "unbalance"],
    "changing": "stay",
    "connection": ["disconnectedness", "unconnectedness"],
    "dress": "undress",
    "easier": ["difficult", "uneasy"],
    "knowing": "ignore",
    "liked": ["dislike", "disliked"],
    "managed": "fail",
    "net": "gross",
    "owned": "unowned",
    "stick": ["dislodge", "move"],
    "turns": "unbend",
    "volume": "softness",
    "wake": ["cause to sleep", "fall asleep", "sleep"],
    "beauty": "ugliness",
    "believed": "disbelieve",
    "busy": "idle",
    "buying": "sell",
    "concerned": "unconcerned",
    "driver": "nondriver",
    "ends": ["begin", "beginning", "middle"],
    "existing": "nonexistent",
    "fix": ["break", "unfasten"],
    "operating": ["disengage", "malfunction"],
    "paying": "default",
    "raise": ["demote", "descent", "level", "lower"],
    "responsibility": ["irresponsibility", "irresponsibleness"],
    "roll": "unwind",
    "suggest": "contraindicate",
    "technical": "nontechnical",
    "youth": "aged",
    "appreciate": "depreciate",
    "bigger": ["little", "small"],
    "breaking": ["conform to", "keep", "make", "promote", "repair"],
    "dry": ["phlegmy", "sweet", "wet"],
    "evil": ["good", "goodness"],
    "excited": ["calm", "stifle", "unexcited"],
    "ordered": ["deregulate", "disarranged", "disorder", "disordered", "incoherent"],
    "prepared": "unprepared",
    "sites": ["arise", "lie", "stand"],
    "arm": "disarm",
    "closer": ["distant", "far"],
    "democratic": "undemocratic",
    "dropped": ["attend to", "recuperate", "sharpen"],
    "figures": "ground",
    "honest": "dishonest",
    "issued": "recall",
    "joined": "disjoin",
    "lee": "windward",
    "lies": ["arise", "sit", "stand"],
    "likes": "dislike",
    "nuclear": "conventional",
    "orders": ["deregulate", "disorder", "disorderliness"],
    "port": "starboard",
    "presence": "absence",
    "reduce": ["blow up", "expand", "gain", "oxidise", "oxidize"],
    "solid": ["gaseous", "hollow", "liquid"],
    "victory": "defeat",
    "citizens": "noncitizen",
    "classic": "nonclassical",
    "clothes": "undress",
    "decisions": ["indecision", "indecisiveness"],
    "entered": ["drop out", "exit"],
    "entirely": "partly",
    "failure": ["achiever", "success"],
    "flat": ["contrasty", "indirectly", "natural", "sharp"],
    "ill": "well",
    "kick": "cheer",
    "links": ["disconnect", "disconnectedness", "dissociate"],
    "pieces": "disassemble",
    "proper": "improper",
    "useful": "useless",
    "willing": ["disinherit", "unwilling"],
    "advanced": ["back", "demote", "fall back", "recede", "regress"],
    "bear": "bull",
    "bringing": "take away",
    "capacity": "incapacity",
    "cheap": "expensive",
    "industrial": "nonindustrial",
    "joint": "separate",
    "mix": "segregate",
    "purchase": "sell",
    "spending": "income",
    "supporting": "negate",
    "tired": ["interest", "refresh", "rested"],
    "treated": ["untempered", "untreated"],
    "turning": "unbend",
    "warm": "cool",
    "afraid": "unafraid",
    "enemy": "friend",
    "filled": ["empty", "unfilled"],
    "fixed": ["break", "unfasten", "unfixed"],
    "intelligence": "stupidity",
    "intended": "unintended",
    "powers": ["inability", "powerlessness"],
    "profit": ["break even", "lose"],
    "wins": ["fail", "fall back", "lose", "losings"],
    "appearance": "disappearance",
    "banks": ["distrust", "mistrust", "withdraw"],
    "brothers": "sister",
    "domestic": ["foreign", "undomestic"],
    "expensive": "cheap",
    "historical": ["ahistorical", "synchronic"],
    "honestly": "dishonestly",
    "honor": ["dishonor", "disrespect"],
    "launch": "abolish",
    "listed": "unlisted",
    "minimum": ["maximal", "maximum"],
    "native": ["adopted", "foreign", "nonnative"],
    "noted": "ignore",
    "planned": "unplanned",
    "sets": "rise",
    "younger": "old",
    "attacks": "defend",
    "charges": ["calm", "discharge", "pay cash"],
    "combined": "uncombined",
    "connected": ["disconnect", "dissociate", "unconnected", "unplug"],
    "download": "upload",
    "email": "snail mail",
    "ending": ["begin", "beginning", "middle"],
    "express": "local",
    "formed": "unformed",
    "illegal": "legal",
    "increasing": ["decrease", "decreasing"],
    "loan": "borrow",
    "selected": "unselected",
    "shared": "unshared",
    "shopping": "boycott",
    "soft": ["forte", "hard", "hardened", "loud", "unvoiced"],
    "stuck": ["dislodge", "move", "unstuck"],
    "suggested": "contraindicate",
    "supported": ["negate", "unsupported"],
    "surprised": "unsurprised",
    "transport": "disenchant",
    "accepted": ["refuse", "reject"],
    "adding": ["subtract", "take away"],
    "allows": ["deny", "disallow", "forbid", "prevent"],
    "appeal": "repel",
    "applied": ["defy", "exempt", "theoretical"],
    "appropriate": "inappropriate",
    "confirmed": ["negate", "unconfirmed"],
    "feed": "starve",
    "grant": "deny",
    "heads": ["foot", "rear", "tail"],
    "hoping": "despair",
    "keeps": ["break", "discontinue", "let", "lose"],
    "lying": ["arise", "sit", "stand"],
    "pulled": ["push", "repel"],
    "requires": "obviate",
    "saved": "lost",
    "scientific": "unscientific",
    "values": ["disesteem", "disrespect"],
    "walked": "ride",
    "angry": "unangry",
    "comfortable": "uncomfortable",
    "concern": "unconcern",
    "emotional": ["cerebral", "unemotional"],
    "falling": ["ascend", "increase", "rise", "rising"],
    "interests": ["bore", "uninterestingness"],
    "internal": "external",
    "laugh": "cry",
    "liberal": "conservative",
    "loves": "hate",
    "pack": "unpack",
    "payment": "nonpayment",
    "recorded": ["erase", "live"],
    "strike": "miss",
    "studio": "location",
    "weak": "strong",
    "advance": ["back", "demote", "fall back", "recede", "regress", "retreat"],
    "chain": "unchain",
    "committed": ["divest", "unattached", "uncommitted"],
    "confidence": "diffidence",
    "equal": ["differ", "inadequate", "unequal"],
    "focused": ["blur", "unfocused"],
    "hits": "miss",
    "leads": ["deficit", "follow"],
    "quiet": ["active", "agitate", "louden", "noisy", "sound", "unquiet", "unquietly"],
    "specifically": "generally",
    "split": "unite",
    "urban": "rural",
    "acts": "refrain",
    "affected": ["unaffected", "unmoved"],
    "approved": "disapprove",
    "claimed": ["disclaim", "forfeit"],
    "determined": "undetermined",
    "distribution": "concentration",
    "extended": "unextended",
    "faster": "slow",
    "fault": ["absolve", "merit"],
    "fill": "empty",
    "friendly": ["hostile", "unfriendly"],
    "ladies": ["lord", "nobleman"],
    "lay": ["arise", "sit", "stand"],
    "lights": ["dark", "extinguish"],
    "mixed": "segregate",
    "properly": "improperly",
    "pure": ["impure", "unsaturated"],
    "reduced": ["blow up", "expand", "gain", "increased", "oxidise", "oxidize"],
    "requirements": "inessential",
    "residents": "nonresident",
    "sat": ["arise", "lie", "stand"],
    "secure": ["insecure", "unfasten"],
    "strange": ["familiar", "native"],
    "blame": "absolve",
    "collected": ["spread", "uncollected", "ungathered"],
    "dying": ["be born", "birth", "nascent"],
    "elected": "appointive",
    "experienced": "inexperienced",
    "falls": ["ascend", "ascent", "increase", "rise"],
    "false": "true",
    "fired": "hire",
    "forgot": ["mind", "remember"],
    "incredible": "credible",
    "inspired": "exhale",
    "launched": "abolish",
    "noticed": ["ignore", "unnoticed"],
    "obvious": "unobvious",
    "passing": ["be born", "fail", "failing", "running"],
    "remaining": "change",
    "slowly": "quickly",
    "worried": "reassure",
    "allowing": ["deny", "disallow", "forbid", "prevent"],
    "begins": "end",
    "charged": ["calm", "discharge", "pay cash", "uncharged"],
    "minor": "major",
    "moments": "inconsequence",
    "opposite": ["alternate", "synonym"],
    "remained": "change",
    "talked": "keep quiet",
    "typically": "atypically",
    "unfortunately": ["fortunately", "luckily"],
    "usual": "unusual",
    "assembly": "disassembly",
    "bright": ["dimmed", "dull"],
    "brings": "take away",
    "capable": "incapable",
    "conservative": "liberal",
    "cutting": ["expand", "switch on"],
    "destroyed": "preserved",
    "draft": "discharge",
    "drunk": "sober",
    "essential": ["adjective", "inessential"],
    "fail": ["manage", "pass", "succeed"],
    "familiar": ["strange", "unfamiliar"],
    "finds": "lose",
    "granted": "deny",
    "guilty": "innocent",
    "improved": ["unimproved", "worsen"],
    "laughing": "cry",
    "perfectly": "imperfectly",
    "relevant": "irrelevant",
    "stands": ["lie", "sit", "yield"],
    "talks": "keep quiet",
    "unable": "able",
    "answers": "question",
    "bomb": "pass",
    "creative": "uncreative",
    "goods": ["bad", "badness", "evil", "evilness"],
    "holds": ["disagree", "let go of"],
    "maximum": ["minimal", "minimum"],
    "adults": "juvenile",
    "appointed": "elective",
    "armed": ["armless", "disarm", "unarmed"],
    "blow": "conserve",
    "careful": "careless",
    "concerns": "unconcern",
    "controlled": "uncontrolled",
    "cry": "laugh",
    "danger": "safety",
    "empty": ["fill", "full"],
    "enjoyed": "suffer",
    "faces": ["avoid", "back"],
    "matches": "disagree",
    "motion": "motionlessness",
    "moves": ["refrain", "rest", "stand still", "stay", "stay in place"],
    "prize": ["disesteem", "disrespect"],
    "reasonable": "unreasonable",
    "receiving": "say farewell",
    "resolution": ["irresoluteness", "preparation"],
    "rural": "urban",
    "singing": "keep quiet",
    "typical": "atypical",
    "wars": ["make peace", "peace"],
    "admit": ["deny", "exclude", "reject"],
    "dedicated": ["desecrated", "undedicated"],
    "drawing": ["deposit", "push", "repel"],
    "heaven": "hell",
    "possibility": "impossibility",
    "random": "nonrandom",
    "represent": "prosecute",
    "sentence": "acquittal",
    "trained": "untrained",
    "understood": "ununderstood",
    "accurate": "inaccurate",
    "competitive": "noncompetitive",
    "harder": ["easy", "lightly", "soft", "voiced"],
    "normally": "remarkably",
    "parent": "child",
    "permanent": "impermanent",
    "personally": "impersonally",
    "pleasure": "pain",
    "representative": "nonrepresentative",
    "stood": ["lie", "sit", "yield"],
    "tight": ["leaky", "loose"],
    "unlike": "like",
    "assets": "liability",
    "button": "unbutton",
    "crying": "laugh",
    "defined": "undefined",
    "depression": ["elation", "natural elevation"],
    "drivers": "nondriver",
    "employment": "unemployment",
    "exclusive": "inclusive",
    "frequently": ["infrequently", "rarely"],
    "grace": "unseemliness",
    "hopefully": "hopelessly",
    "importance": "unimportance",
    "latter": "former",
    "pregnant": "nonpregnant",
    "promote": "demote",
    "sleeping": ["wake", "waking"],
    "attend": "miss",
    "declared": "undeclared",
    "dirty": "clean",
    "doctors": "break",
    "earned": "unearned",
    "existence": ["nonbeing", "nonexistence"],
    "experiences": "inexperience",
    "expression": "misconstruction",
    "headed": ["headless", "unheaded"],
    "interior": ["exterior", "outside"],
    "joy": ["sadden", "sorrow"],
    "retail": "wholesale",
    "shame": "honor",
    "ships": "disembark",
    "somewhat": ["immoderately", "unreasonably"],
    "staying": ["change", "depart", "move"],
    "stronger": ["impotent", "weak"],
    "absolute": "relative",
    "calm": ["agitate", "discomposure", "stimulate", "stormy"],
    "checked": "disagree",
    "constant": "inconstant",
    "driven": "attract",
    "exciting": ["calm", "stifle", "unexciting"],
    "expansion": "contraction",
    "heavily": "lightly",
    "hide": "show",
    "incident": "basic",
    "linked": ["disconnect", "dissociate"],
    "manage": "fail",
    "quit": ["continue", "enter", "stay", "take office"],
    "refused": ["accept", "admit", "allow", "lend oneself"],
    "significantly": "insignificantly",
    "sing": "keep quiet",
    "wet": "dry",
    "ages": "rejuvenate",
    "attractive": ["repulsive", "unattractive"],
    "broad": "narrow",
    "deaths": "birth",
    "drawn": ["deposit", "push", "repel"],
    "hidden": "show",
    "letting": ["disallow", "forbid", "prevent"],
    "loud": ["piano", "soft", "softly"],
    "officially": "unofficially",
    "peak": "bottom out",
    "puts": ["call option", "divest"],
    "raw": "cooked",
    "represented": ["prosecute", "undelineated"],
    "secondary": "primary",
    "stayed": ["change", "depart", "move"],
    "suffering": ["be well", "enjoy"],
    "ultimate": "proximate",
    "unknown": ["acquaintance", "known"],
    "attached": ["detach", "detached", "unattached"],
    "attacked": "defend",
    "blind": "sighted",
    "differences": "sameness",
    "engaged": ["disengage", "fire"],
    "expressed": "implicit",
    "external": "internal",
    "immediate": "mediate",
    "license": "decertify",
    "presidential": "unpresidential",
    "registered": "unregistered",
    "regularly": "irregularly",
    "rising": ["fall", "falling", "go to bed", "lie down", "set", "sit down", "turn in", "wane"],
    "shipping": "disembark",
    "suffered": ["be well", "enjoy"],
    "survive": "succumb",
    "tall": "short",
    "adopted": "native",
    "comedy": "tragedy",
    "covers": "uncover",
    "defeat": "victory",
    "defence": ["offence", "offense", "prosecution"],
    "exact": "inexact",
    "exposed": "cover",
    "fed": "starve",
    "injured": "uninjured",
    "lets": ["disallow", "forbid", "prevent"],
    "loans": "borrow",
    "lock": ["disengage", "unlock"],
    "musical": ["unmelodious", "unmusical"],
    "opposed": "unopposed",
    "organized": ["disorganise", "disorganize", "disorganized", "unorganized"],
    "protected": "unprotected",
    "recording": "erase",
    "suspect": ["plaintiff", "trust"],
    "swear": ["distrust", "mistrust"],
    "tie": ["disconnect", "untie"],
    "valuable": "worthless",
    "wealth": "poverty",
    "wise": "foolish",
    "aged": ["rejuvenate", "young"],
    "approval": "disapproval",
    "convention": "unconventionality",
    "employee": "employer",
    "facing": ["avoid", "back"],
    "fairly": ["immoderately", "unfairly", "unreasonably"],
    "founded": "abolish",
    "functions": "malfunction",
    "inner": "outer",
    "lift": ["fall", "lower"],
    "marked": ["ignore", "unmarked"],
    "operate": ["disengage", "malfunction"],
    "racing": "linger",
    "sons": ["daughter", "girl"],
    "admitted": ["deny", "exclude", "reject"],
    "colour": ["black-and-white", "colorlessness", "discolor"],
    "effectively": ["ineffectively", "inefficaciously"],
    "extensive": "intensive",
    "faced": ["avoid", "back", "faceless"],
    "gained": ["fall back", "lose", "reduce"],
    "improvement": "decline",
    "junior": "senior",
    "marks": "ignore",
    "pride": "humility",
    "riding": "walk",
    "rough": ["cut", "smooth"],
    "studied": "unstudied",
    "suggests": "contraindicate",
    "tone": "atonicity",
    "universal": ["particular", "particular proposition"],
    "consistent": ["incoherent", "inconsistent", "unreproducible"],
    "continuing": "discontinue",
    "ignore": ["know", "notice"],
    "involving": "obviate",
    "naturally": ["artificially", "unnaturally"],
    "necessarily": "unnecessarily",
    "payments": "nonpayment",
    "practical": "impractical",
    "primarily": "secondarily",
    "proved": ["disprove", "unproved"],
    "relative": "absolute",
    "represents": "prosecute",
    "rush": ["delay", "linger"],
    "sharp": ["dull", "flat", "natural"],
    "stable": "unstable",
    "supplies": ["demand", "recall"],
    "temporary": "permanent",
    "attended": ["miss", "unaccompanied"],
    "clothing": "undress",
    "complicated": "simplify",
    "confused": "clearheaded",
    "consequences": "inconsequence",
    "defend": ["attack", "prosecute"],
    "divided": ["multiply", "unite", "united"],
    "gotten": ["end", "leave", "take away"],
    "impressive": "unimpressive",
    "joining": "disjoin",
    "loving": ["hate", "unloving"],
    "mount": ["hop out", "wane"],
    "nights": "day",
    "purchased": "sell",
    "reputation": "disrepute",
    "rolling": "unwind",
    "strongly": "weakly",
    "thin": ["fat", "full", "gain", "thick", "thicken", "thickly"],
    "tied": ["disconnect", "unlaced", "untie", "untied"],
    "awful": "nice",
    "belief": "unbelief",
    "bound": ["free", "unbind", "unbound", "untie"],
    "breaks": ["conform to", "keep", "make", "promote", "repair"],
    "carefully": ["carelessly", "incautiously"],
    "cats": "keep down",
    "closing": ["open", "opening"],
    "cloud": "clear up",
    "colors": ["colorlessness", "discolor"],
    "drew": ["deposit", "push", "repel"],
    "establish": ["abolish", "disprove"],
    "extension": "flexion",
    "hitting": "miss",
    "increases": ["decrease", "decrement"],
    "locations": "studio",
    "loose": ["affixed", "compact", "confine", "stiffen", "tight"],
    "moral": "immoral",
    "offensive": ["defensive", "euphemistic", "inoffensive", "savory"],
    "package": ["hardware", "unbox"],
    "pointed": "pointless",
    "poverty": "wealth",
    "qualified": ["disqualify", "unqualified"],
    "sensitive": ["insensible", "insensitive"],
    "silence": ["louden", "sound"],
    "superior": ["adscript", "inferior", "subscript"],
    "thick": ["thin", "thinly"],
    "violent": "nonviolent",
    "bars": "unbar",
    "covering": "uncover",
    "curious": "incurious",
    "encourage": "discourage",
    "featuring": "lack",
    "formal": "informal",
    "gross": "net",
    "hungry": "thirsty",
    "informed": "uninformed",
    "innocent": "guilty",
    "losses": ["gain", "winnings"],
    "minds": "forget",
    "passes": ["be born", "fail", "failing"],
    "penalty": "reward",
    "scheduled": "unscheduled",
    "spoken": "written",
    "successfully": "unsuccessfully",
    "suffer": ["be well", "enjoy"],
    "uncle": "aunt",
    "unusual": ["familiar", "usual"],
    "asks": "obviate",
    "awareness": "incognizance",
    "badly": ["advantageously", "well"],
    "concrete": "abstract",
    "featured": "lack",
    "happiness": ["sadness", "unhappiness"],
    "mini": ["maxi", "midi"],
    "pleased": ["displease", "displeased"],
    "pushing": "pull",
    "retired": ["advance", "get up", "turn out"],
    "settled": ["float", "unsettled"],
    "tape": "erase",
    "believes": ["disbelieve", "unbelief"],
    "blocks": ["free", "remember", "unblock", "unfreeze", "unstuff"],
    "boring": "interest",
    "checking": "disagree",
    "confident": "diffident",
    "custom": "ready-made",
    "denied": ["admit", "allow"],
    "grounds": "figure",
    "helpful": "unhelpful",
    "locked": ["disengage", "unlock"],
    "opens": ["close", "fold"],
    "plain": ["cheer", "fancy", "patterned"],
    "pushed": "pull",
    "raising": ["demote", "level", "lower"],
    "rear": ["front", "head", "level"],
    "romantic": "classicist",
    "sisters": "brother",
    "swimming": "sink",
    "welfare": "ill-being",
    "winners": "loser",
    "wire": "unwire",
    "worker": "nonworker",
    "belt": "unbelt",
    "cuts": ["expand", "switch on"],
    "diamond": "outfield",
    "dressed": "undress",
    "efficient": "inefficient",
    "employed": ["fire", "unemployed"],
    "enjoying": "suffer",
    "entering": ["drop out", "exit"],
    "handed": "handless",
    "odd": "even",
    "ordinary": "extraordinary",
    "participate": "drop out",
    "rarely": "often",
    "sexy": ["anaphrodisiac", "unsexy"],
    "soil": "clean",
    "struck": "miss",
    "suck": "bottlefeed",
    "supports": "negate",
    "ugly": "beautiful",
    "comfort": "discomfort",
    "controls": "unrestraint",
    "demands": ["obviate", "supply"],
    "dies": "be born",
    "dramatic": ["lyric", "undramatic"],
    "evolution": "devolution",
    "hired": ["fire", "unchartered"],
    "illness": "wellness",
    "kings": ["female monarch", "queen"],
    "lowest": "high",
    "minority": "majority",
    "priority": "posteriority",
    "promotion": "demotion",
    "remote": "close",
    "repair": "break",
    "root": "descendant",
    "acquired": "lose",
    "alliance": "nonalignment",
    "buried": ["remember", "unburied"],
    "conclusion": "beginning",
    "confirm": "negate",
    "contracts": ["expand", "stretch", "widen"],
    "convinced": "unconvinced",
    "decent": ["improperly", "indecent"],
    "decline": ["accept", "ascent", "better", "improvement"],
    "delay": "rush",
    "downtown": "uptown",
    "enemies": "friend",
    "forgotten": ["mind", "remember"],
    "hire": "fire",
    "hopes": "despair",
    "insane": "sane",
    "managing": "fail",
    "nurse": "bottlefeed",
    "organic": ["functional", "inorganic"],
    "recall": ["forget", "issue"],
    "smooth": ["rough", "roughen", "staccato"],
    "stops": ["begin", "continuant consonant", "continue", "start"],
    "string": "unstring",
    "sudden": "gradual",
    "assigned": "unassigned",
    "associate": "dissociate",
    "citizen": "noncitizen",
    "cleaning": "dirty",
    "damaged": "undamaged",
    "equally": ["unequally", "unevenly"],
    "fallen": ["ascend", "increase", "rise"],
    "fitness": "unfitness",
    "intense": "mild",
    "keys": "atonality",
    "liquid": ["gaseous", "solid", "unmelted"],
    "narrow": ["broad-minded", "diversify", "wide", "widen"],
    "observed": ["break", "disrespect"],
    "reduction": "increase",
    "refuse": ["accept", "admit", "allow", "lend oneself"],
    "subsequent": "antecedent",
    "visible": "invisible",
    "adds": ["subtract", "take away"],
    "arrive": "leave",
    "commonly": "remarkably",
    "connect": ["disconnect", "dissociate", "unplug"],
    "defensive": "offensive",
    "efficiency": "inefficiency",
    "females": "male",
    "incredibly": ["believably", "credibly"],
    "kicked": "cheer",
    "races": "linger",
    "resident": ["migratory", "nonresident"],
    "sucks": "bottlefeed",
    "valid": "invalid",
    "collect": "spread",
    "genuine": "counterfeit",
    "honour": ["dishonor", "disrespect"],
    "hook": ["undercharge", "unhook"],
    "improving": "worsen",
    "rejected": ["accept", "admit", "approve"],
    "reverse": ["forward", "obverse"],
    "settle": "float",
    "spell": "unspell",
    "tongue": "artificial language",
    "asleep": "awake",
    "automatic": "manual",
    "begun": "end",
    "comprehensive": "noncomprehensive",
    "consent": "refuse",
    "drove": "attract",
    "engage": ["disengage", "fire"],
    "extraordinary": "ordinary",
    "meets": "diverge",
    "objective": "subjective",
    "profits": ["break even", "lose", "losings"],
    "reducing": ["blow up", "expand", "gain", "oxidise", "oxidize"],
    "regard": ["disesteem", "disrespect", "inattentiveness"],
    "representing": "prosecute",
    "strip": "dress",
    "banking": ["distrust", "mistrust", "withdraw"],
    "corruption": "incorruptness",
    "crossed": ["uncross", "uncrossed"],
    "exit": ["be born", "enter"],
    "expand": "contract",
    "fancy": "plain",
    "grateful": "ungrateful",
    "indicate": "contraindicate",
    "knock": "praise",
    "operated": ["disengage", "malfunction"],
    "painted": "unpainted",
    "pulling": ["push", "repel"],
    "rob": "undercharge",
    "stretch": "shrink",
    "ties": ["disconnect", "untie"],
    "voices": "devoice",
    "wishes": "begrudge",
    "absence": "presence",
    "bears": "bull",
    "boxes": "unbox",
    "bull": "bear",
    "couples": "uncouple",
    "deny": ["admit", "allow"],
    "ease": "difficulty",
    "fame": "infamy",
    "flood": "ebbtide",
    "indicated": "contraindicate",
    "involves": "obviate",
    "progressive": ["conservative", "regressive"],
    "rally": "demobilize",
    "rapidly": "slowly",
    "roots": "descendant",
    "shops": "boycott",
    "tail": "head",
    "texts": "trade edition",
    "alert": "unalert",
    "brave": ["cowardly", "timid"],
    "claiming": ["disclaim", "forfeit"],
    "commit": "divest",
    "constitutional": "unconstitutional",
    "crossing": "uncross",
    "defending": ["attack", "prosecute"],
    "density": "distribution",
    "difficulty": "ease",
    "dropping": ["attend to", "recuperate", "sharpen"],
    "drops": ["attend to", "recuperate", "sharpen"],
    "mechanical": "nonmechanical",
    "participation": ["non-engagement", "non-involvement", "nonparticipation"],
    "proven": ["disprove", "unproved"],
    "radical": "cauline",
    "remembered": "forget",
    "requested": "unrequested",
    "residential": "nonresidential",
    "reward": ["dishonor", "penalty"],
    "rings": "open chain",
    "substantial": "insubstantial",
    "uniform": ["differentiated", "multiform"],
    "aggressive": "unaggressive",
    "connections": ["disconnectedness", "unconnectedness"],
    "courage": "cowardice",
    "encouraged": "discourage",
    "frozen": ["boil", "unblock", "unfreeze", "unfrozen"],
    "hiding": "show",
    "invest": "divest",
    "manual": "automatic",
    "mothers": ["father", "male parent"],
    "nursing": "bottlefeed",
    "occupied": "unoccupied",
    "painful": "painless",
    "preparation": "resolution",
    "releases": ["block", "confine", "freeze", "hold"],
    "sufficient": "insufficient",
    "survived": "succumb",
    "walks": "ride",
    "arranged": ["disarrange", "disarranged"],
    "attending": ["inattention", "miss", "nonattendance"],
    "attracted": "repel",
    "biological": "adoptive",
    "blocked": ["free", "remember", "unblock", "unfreeze", "unstuff"],
    "boards": "get off",
    "checks": "disagree",
    "disorder": ["order", "orderliness"],
    "distributed": ["concentrated", "gather"],
    "dynamic": ["stative", "undynamic"],
    "engagement": ["non-engagement", "non-involvement", "nonparticipation"],
    "fewer": ["many", "more"],
    "mask": "unmask",
    "packed": "unpack",
    "piano": "forte",
    "praise": "criticize",
    "stability": ["inconstancy", "instability", "unstableness"],
    "steady": ["unsteadily", "unsteady"],
    "terminal": "intermediate",
    "unlikely": ["likely", "probable"],
    "collective": "distributive",
    "cooperation": "competition",
    "darkness": ["light", "lightness"],
    "deeper": "shallow",
    "enable": "disable",
    "equity": ["inequity", "unfairness"],
    "failing": ["manage", "pass", "passing", "succeed"],
    "finishing": ["begin", "start"],
    "hardware": "software",
    "hurts": "be well",
    "intellectual": ["emotional", "nonintellectual"],
    "involvement": ["non-engagement", "non-involvement", "nonparticipation"],
    "partly": "wholly",
    "racial": "nonracial",
    "seal": "unseal",
    "separated": "unite",
    "talented": "untalented",
    "touched": ["unmoved", "untouched"],
    "wisdom": ["folly", "unsoundness"],
    "alien": ["acquaintance", "citizen"],
    "attacking": "defend",
    "awkward": "graceful",
    "celebrity": "infamy",
    "default": ["pay up", "payment"],
    "derived": "underived",
    "disabled": "enable",
    "distinct": "indistinct",
    "educated": "uneducated",
    "eligible": "ineligible",
    "followers": "leader",
    "funded": "unfunded",
    "integrated": ["differentiate", "disintegrate", "nonintegrated", "segregate", "segregated"],
    "intelligent": "unintelligent",
    "lighting": ["dark", "extinguish"],
    "loop": ["open circuit", "uncoil"],
    "recover": "deteriorate",
    "relax": ["stiffen", "strain", "tense"],
    "reliable": ["undependable", "unreliable"],
    "rely": ["distrust", "mistrust"],
    "stopping": ["begin", "continue", "start"],
    "succeed": ["fail", "precede"],
    "volunteers": "draftee",
    "wore": "refresh",
    "worthy": "unworthy",
    "acted": "refrain",
    "bloody": "bloodless",
    "breathing": "breathless",
    "con": "pro",
    "consideration": ["inconsideration", "thoughtlessness"],
    "crucial": "noncrucial",
    "daughters": ["boy", "son"],
    "dependent": "independent",
    "drives": "attract",
    "equipped": ["unequipped", "unfurnished"],
    "expanded": ["contract", "contracted"],
    "feeding": "starve",
    "highlights": ["background", "play down"],
    "hoped": "despair",
    "involve": "obviate",
    "mature": ["green", "immature", "unfledged"],
    "peaceful": "unpeaceful",
    "pin": "unpin",
    "promoting": "demote",
    "publicly": "privately",
    "satisfied": ["dissatisfy", "fall short of"],
    "specialist": "generalist",
    "stranger": ["acquaintance", "familiar", "native"],
    "surprising": "unsurprising",
    "volunteer": "draftee",
    "acceptable": "unacceptable",
    "allies": "foe",
    "composed": "discomposed",
    "concentration": ["dilution", "distribution"],
    "credits": ["cash", "debit"],
    "dawn": "sunset",
    "firing": "hire",
    "fits": "disagree",
    "frequent": ["boycott", "infrequent"],
    "gathered": ["spread", "uncollected", "ungathered"],
    "ignored": ["know", "notice"],
    "improvements": "decline",
    "moderate": "immoderate",
    "parallel": ["oblique", "perpendicular"],
    "pit": "heaven",
    "sized": "unsized",
    "traveling": "stay in place",
    "tune": "untune",
    "utility": ["inutility", "uselessness"],
    "weed": "cultivated plant",
    "addressed": "unaddressed",
    "backed": ["advance", "backless", "front", "veer"],
    "bold": "timid",
    "classical": "nonclassical",
    "classified": ["declassify", "unclassified"],
    "clip": "unclip",
    "concepts": "misconception",
    "disappeared": "appear",
    "equality": "inequality",
    "fails": ["manage", "pass", "succeed"],
    "fiscal": "nonfinancial",
    "intervention": ["noninterference", "nonintervention"],
    "mounted": ["hop out", "wane"],
    "mutual": "nonreciprocal",
    "offense": ["defence", "defense"],
    "oral": ["aboral", "anal"],
    "pays": "default",
    "requirement": "inessential",
    "stays": ["change", "depart", "move"],
    "worn": ["new", "refresh"],
    "yea": "nay",
    "accompanied": "unaccompanied",
    "beliefs": "unbelief",
    "considerable": "inconsiderable",
    "conventional": ["nuclear", "unconventional"],
    "employers": "employee",
    "focusing": "blur",
    "gains": ["fall back", "lose", "loss", "reduce"],
    "gathering": ["disassembly", "spread"],
    "handled": "handleless",
    "inquiry": "answer",
    "loaded": "unloaded",
    "mercy": "mercilessness",
    "outer": ["inner", "safe"],
    "powered": "unpowered",
    "recovered": "deteriorate",
    "rude": "civil",
    "screw": "unscrew",
    "strikes": "miss",
    "suggesting": "contraindicate",
    "vary": "conform",
    "accuracy": "inaccuracy",
    "applying": ["defy", "exempt"],
    "artificial": "natural",
    "beneath": "above",
    "consistently": ["inconsistently", "unsystematically"],
    "deposit": ["dislodge", "withdraw"],
    "emails": "snail mail",
    "export": "import",
    "fastest": "slow",
    "functional": ["nonfunctional", "organic"],
    "gather": "spread",
    "indicates": "contraindicate",
    "knocked": "praise",
    "landed": "landless",
    "laughed": "cry",
    "modified": "unmodified",
    "neutral": ["chromatic", "negative", "positive"],
    "noble": ["ignoble", "lady", "lowborn", "noblewoman"],
    "oldest": ["new", "young"],
    "popularity": "unpopularity",
    "professionals": "amateur",
    "relate": "dissociate",
    "sacred": "profane",
    "securities": "insecurity",
    "supplied": "recall",
    "toxic": "nontoxic",
    "unions": ["disunion", "separation"],
    "upgrade": ["demote", "descent", "downgrade"],
    "wider": "narrow",
    "wound": "unwind",
    "actively": "passively",
    "applies": ["defy", "exempt"],
    "asset": "liability",
    "backing": ["advance", "front", "veer"],
    "blessed": ["curse", "cursed", "desecrate"],
    "burden": "unburden",
    "certified": ["decertify", "uncertified"],
    "civilian": ["military", "serviceman"],
    "coalition": "nonalignment",
    "complain": "cheer",
    "controversial": "uncontroversial",
    "discipline": "indiscipline",
    "dominant": ["recessive", "subordinate"],
    "hiring": "fire",
    "hosts": "parasite",
    "implemented": ["exempt", "unenforced"],
    "opponents": "agonist",
    "outdoor": "indoor",
    "rolls": "unwind",
    "secured": "unfasten",
    "shed": "persistent",
    "sponsored": "boycott",
    "strict": "indulgent",
    "unexpected": "expected",
    "accidentally": ["deliberately", "intentionally"],
    "amateur": "professional",
    "appeals": "repel",
    "bearing": "nonbearing",
    "cheaper": "expensive",
    "climb": ["descent", "wane"],
    "delete": "record",
    "demonstrated": "disprove",
    "developments": ["devolution", "nondevelopment"],
    "employer": "employee",
    "integration": "segregation",
    "legitimate": ["criminalise", "criminalize", "illegitimate", "outlaw"],
    "longest": ["short", "unretentive"],
    "nasty": "nice",
    "permit": ["disallow", "forbid", "prevent"],
    "pleasant": "unpleasant",
    "productive": ["consumptive", "unproductive"],
    "shorter": ["long", "retentive", "tall"],
    "slight": "much",
    "socialist": "capitalistic",
    "twist": ["unbend", "untwist"],
    "unemployment": "employment",
    "useless": "useful",
    "winds": "unwind",
    "woke": ["cause to sleep", "fall asleep", "sleep"],
    "abilities": "inability",
    "blown": "conserve",
    "closest": ["distant", "far"],
    "continuous": "discontinuous",
    "correctly": ["incorrectly", "wrongly"],
    "declined": ["accept", "better"],
    "difficulties": "ease",
    "forcing": ["pull", "push"],
    "gravity": "levity",
    "highlight": ["background", "play down"],
    "identical": "fraternal",
    "legally": "unlawfully",
    "lied": ["arise", "sit", "stand"],
    "males": "female",
    "operational": "nonoperational",
    "relating": "dissociate",
    "rolled": "unwind",
    "sink": ["float", "source"],
    "snap": "inelasticity",
    "swim": "sink",
    "vulnerable": "invulnerable",
    "attract": "repel",
    "blowing": "conserve",
    "bored": "interest",
    "catching": "unhitch",
    "chronic": "acute",
    "cleared": ["bounce", "clutter", "convict", "overcast", "uncleared"],
    "communicate": "excommunicate",
    "convicted": "acquit",
    "delayed": "rush",
    "demonstrate": "disprove",
    "dismissed": "hire",
    "generous": ["stingy", "ungenerous"],
    "hated": "love",
    "implement": "exempt",
    "incorporated": "disintegrate",
    "loyal": ["disloyal", "unpatriotic"],
    "opponent": "agonist",
    "patience": "impatience",
    "pollution": "decontamination",
    "precisely": ["imprecisely", "inexactly"],
    "regards": ["disesteem", "disrespect", "inattentiveness"],
    "resist": ["lend oneself", "surrender"],
    "striking": "miss",
    "trusted": ["distrust", "mistrust"],
    "volumes": "softness",
    "wireless": "wired",
    "wrap": ["unwind", "unwrap"],
    "beings": ["nonbeing", "nonexistence"],
    "bulk": "minority",
    "coastal": "inland",
    "colored": ["discolor", "uncolored"],
    "cried": "laugh",
    "distant": "close",
    "filling": "empty",
    "invested": "divest",
    "lit": ["extinguish", "unlighted"],
    "partially": "wholly",
    "participating": "drop out",
    "preserve": "discontinue",
    "qualify": "disqualify",
    "receives": "say farewell",
    "restricted": ["derestrict", "unrestricted"],
        /* ================================================================
     *  Humanities and semiotics extensions
     * ================================================================ */

    /* --- Semiotics and structuralism --- */
    "paradigm":         "syntagm",
    "syntagm":          "paradigm",
    "paradigmatic":     "syntagmatic",
    "syntagmatic":      "paradigmatic",
    "marked":           "unmarked",
    "unmarked":         "marked",
    "icon":             "symbol",
    "index":            "icon",
    "symptom":          "symbol",
    "langue":           "parole",
    "parole":           "langue",
    "synchrony":        "diachrony",
    "diachrony":        "synchrony",
    "synchronous":      "diachronic",
    "diachronic":       "synchronous",
    "signifier":        "signified",
    "signified":        "signifier",
    "denotation":       "connotation",
    "connotation":      "denotation",
    "encoding":         "decoding",
    "decoding":         "encoding",
    "addresser":        "addressee",
    "addressee":        "addresser",
    "sender":           "receiver",
    "receiver":         "sender",
    "competence":       "performance",
    "performance":      "competence",
    "narrative":        "description",
    "description":      "narrative",
    "story":            "plot",
    "plot":             "story",
    "fabula":           "sjuzhet",
    "sjuzhet":          "fabula",
    "diegesis":         "mimesis",
    "mimesis":          "diegesis",
    "utterance":        "enunciation",
    "enunciation":      "utterance",
    "text":             "work",
    "work":             "text",
    "code":             "message",
    "message":          "code",
    "signal":           "noise",
    "noise":            "signal",

    /* --- Phenomenology and consciousness --- */
    "noesis":           "noema",
    "noema":            "noesis",
    "noetic":           "noematic",
    "noematic":         "noetic",
    "prepredicative":   "predicative",
    "predicative":      "prepredicative",
    "lived":            "objective",
    "objective":        "lived",
    "ready-to-hand":    "present-at-hand",
    "present-at-hand":  "ready-to-hand",
    "attunement":       "understanding",
    "understanding":    "attunement",
    "thrownness":       "projection",
    "projection":       "thrownness",
    "facticity":        "transcendence",
    "transcendence":    "facticity",
    "being-with":       "being-alone",
    "being-alone":      "being-with",
    "authentic":        "inauthentic",
    "inauthentic":      "authentic",
    "recollection":     "anticipation",
    "anticipation":     ["recollection", "nostalgia"],
    "reflective":       "prereflective",
    "prereflective":    "reflective",
    "intentional":      "nonintentional",
    "nonintentional":   "intentional",
    "ekstatic":         "enstatic",
    "enstatic":         "ekstatic",

    /* --- Myth, ritual, and the sacred --- */
    "liminal":          "liminoid",
    "liminoid":         "liminal",
    "communitas":       "structure",
    "structure":        "communitas",
    "katabasis":        "anabasis",
    "anabasis":         "katabasis",
    "genesis":          "apocalypse",
    "apocalypse":       "genesis",
    "protology":        "eschatology",
    "eschatology":      "protology",
    "cosmogony":        "cosmology",
    "cosmology":        "cosmogony",
    "theogony":         "anthropogony",
    "anthropogony":     "theogony",
    "sacrifice":        "oblation",
    "oblation":         "sacrifice",
    "initiation":       "expulsion",
    "expulsion":        "initiation",
    "pilgrimage":       "exile",
    "exile":            "pilgrimage",
    "sacred":           "demonic",
    "demonic":          "sacred",
    "numinous":         "profane",
    "profane":          ["numinous", "initiate"],
    "initiate":         "profane",
    "taboo":            "permitted",
    "permitted":        "taboo",
    "pure":             "polluted",
    "polluted":         "pure",
    "consecrated":      "desecrated",
    "desecrated":       "consecrated",

    /* --- Ethics and value --- */
    "supererogatory":   "obligatory",
    "obligatory":       "supererogatory",
    "permissible":      "impermissible",
    "impermissible":    "permissible",
    "meritorious":      "blameworthy",
    "blameworthy":      "meritorious",
    "praiseworthy":     "culpable",
    "culpable":         "praiseworthy",
    "deontological":    ["consequentialist", "teleological"],
    "consequentialist": "deontological",
    "teleological":     "deontological",
    "rigorism":         "laxism",
    "laxism":           "rigorism",
    "heroic":           "base",
    "base":             "heroic",
    "magnanimous":      "pusillanimous",
    "pusillanimous":    "magnanimous",
    "continence":       "incontinence",
    "incontinence":     "continence",
    "temperance":       "intemperance",
    "intemperance":     "temperance",
    "equanimity":       "perturbation",
    "perturbation":     "equanimity",

    /* --- Aesthetics and criticism --- */
    "sublime":          "beautiful",
    "beautiful":        "sublime",
    "kitsch":           "sincere",
    "sincere":          "kitsch",
    "camp":             "earnest",
    "earnest":          "camp",
    "baroque":          "classical",
    "classical":        "baroque",
    "epic":             "lyric",
    "lyric":            "epic",
    "elegiac":          "celebratory",
    "celebratory":      "elegiac",
    "grotesque":        "serene",
    "serene":           "grotesque",
    "garish":           "tasteful",
    "tasteful":         "garish",
    "mannered":         "natural",
    "natural":          "mannered",
    "ornate":           "austere",
    "austere":          "ornate",
    "decadent":         "vigorous",
    "vigorous":         "decadent",
    "sentimental":      "ironic",
    "ironic":           "sentimental",
    "cerebral":         "visceral",
    "visceral":         "cerebral",
    "refined":          "coarse",
    "coarse":           "refined",
    "ingenuous":        "sophisticated",
    "sophisticated":    "ingenuous",

    /* --- Politics and ideology --- */
    "radical":          "moderate",
    "moderate":         "radical",
    "reactionary":      "revolutionary",
    "revolutionary":    "reactionary",
    "authoritarian":    "libertarian",
    "libertarian":      "authoritarian",
    "populist":         "elitist",
    "elitist":          "populist",
    "federal":          "unitary",
    "unitary":          "federal",
    "cosmopolitan":     "nationalist",
    "nationalist":      "cosmopolitan",
    "totalitarian":     "pluralist",
    "pluralist":        "totalitarian",
    "oligarchic":       "democratic",
    "democratic":       "oligarchic",
    "absolutist":       "constitutionalist",
    "constitutionalist":"absolutist",
    "hegemonic":        ["counter-hegemonic", "subaltern"],
    "counter-hegemonic":"hegemonic",
    "subaltern":        "hegemonic",

    /* --- Psychoanalysis --- */
    "manifest":         ["latent", "occult"],
    "latent":           "manifest",
    "occult":           "manifest",
    "cathexis":         "decathexis",
    "decathexis":       "cathexis",
    "sublimation":      ["regression", "abjection"],
    "regression":       "sublimation",
    "abjection":        "sublimation",
    "repression":       "expression",
    "expression":       "repression",
    "eros":             "thanatos",
    "thanatos":         "eros",
    "narcissism":       "object-love",
    "object-love":      "narcissism",
    "introjection":     "projection",
    "projection":       "introjection",
    "melancholia":      "mourning",
    "mourning":         "melancholia",
    "neurosis":         "psychosis",
    "psychosis":        "neurosis",
    "anal":             "oral",
    "oral":             "anal",

    /* --- Anthropology and kinship --- */
    "kin":              "stranger",
    "stranger":         "kin",
    "consanguineal":    "affinal",
    "affinal":          "consanguineal",
    "endogamous":       "exogamous",
    "exogamous":        "endogamous",
    "exogamy":          "endogamy",
    "endogamy":         "exogamy",
    "patrilineal":      "matrilineal",
    "matrilineal":      "patrilineal",
    "patrilocal":       "matrilocal",
    "matrilocal":       "patrilocal",
    "bridewealth":      "dowry",
    "dowry":            "bridewealth",
    "gift":             "commodity",
    "commodity":        "gift",
    "reciprocity":      "redistribution",
    "redistribution":   "reciprocity",
    "potlatch":         "accumulation",
    "accumulation":     "potlatch",
    "holistic":         "atomistic",
    "atomistic":        "holistic",

    /* --- Theology and metaphysics --- */
    "apophatic":        ["kataphatic", "cataphatic"],
    "kataphatic":       "apophatic",
    "cataphatic":       "apophatic",
    "theistic":         "atheistic",
    "atheistic":        "theistic",
    "grace":            "sin",
    "sin":              "grace",
    "salvation":        "damnation",
    "damnation":        "salvation",
    "incarnation":      "excarnation",
    "excarnation":      "incarnation",
    "kenosis":          "plerosis",
    "plerosis":         "kenosis",
    "immanent":         "transcendent",
    "transcendent":     "immanent",
    "univocal":         ["equivocal", "analogical"],
    "equivocal":        "univocal",
    "analogical":       "univocal",
    "theodicy":         "anti-theodicy",
    "anti-theodicy":    "theodicy",
    "providence":       "chance",
    "chance":           "providence",
    "predestination":   "free-will",
    "free-will":        "predestination",

    /* --- Literary and rhetorical --- */
    "prose":            "poetry",
    "poetry":           "prose",
    "allegory":         "symbol",
    "symbol":           ["icon", "allegory"],
    "irony":            "sincerity",
    "sincerity":        "irony",
    "satire":           "encomium",
    "encomium":         "satire",
    "elegy":            "ode",
    "ode":              "elegy",
    "rhetoric":         "logic",
    "logic":            "rhetoric",
    "trope":            "scheme",
    "scheme":           "trope",
    "hyperbole":        "litotes",
    "litotes":          "hyperbole",
    "metaphor":         ["metonymy", "simile"],
    "metonymy":         ["metaphor", "synecdoche"],
    "simile":           "metaphor",
    "synecdoche":       "metonymy",
    "anaphora":         "epistrophe",
    "epistrophe":       "anaphora",
    "asyndeton":        "polysyndeton",
    "polysyndeton":     "asyndeton",
    "prolepsis":        "analepsis",
    "analepsis":        "prolepsis",
    "apostrophe":       "ellipsis",
    "ellipsis":         "apostrophe",
    "paronomasia":      "antanaclasis",
    "antanaclasis":     "paronomasia",
    "zeugma":           "syllepsis",
    "syllepsis":        "zeugma",

    /* --- Mood and affect --- */
    "melancholy":       "cheerfulness",
    "cheerfulness":     "melancholy",
    "nostalgia":        "anticipation",
    "serenity":         "agitation",
    "agitation":        "serenity",
    "dread":            "hope",
    "hope":             "dread",
    "ecstasy":          "despair",
    "despair":          "ecstasy",
    "ennui":            "vitality",
    "vitality":         "ennui",
    "anguish":          "peace",
    "peace":            "anguish",
    "elation":          "dejection",
    "dejection":        "elation",
    "euphoria":         "dysphoria",
    "dysphoria":        "euphoria",
    "reverie":          "attention",
    "attention":        "reverie",
    "listlessness":     "eagerness",
    "eagerness":        "listlessness",

    /* --- Somatic and perceptual --- */
    "proximal":         "distal",
    "distal":           "proximal",
    "tactile":          "visual",
    "visual":           "tactile",
    "somatic":          "psychic",
    "psychic":          "somatic",
    "proprioceptive":   "exteroceptive",
    "exteroceptive":    "proprioceptive",
    "interoceptive":    "exteroceptive",
    "kinesthetic":      "static",
    "static":           "kinesthetic",
    "gustatory":        "olfactory",
    "olfactory":        "gustatory",
    "voluntary":        "involuntary",
    "involuntary":      "voluntary",
    "systolic":         "diastolic",
    "diastolic":        "systolic",
    "sympathetic":      "parasympathetic",
    "parasympathetic":  "sympathetic",

    /* --- General humanities extensions --- */
    "canonical":        "apocryphal",
    "apocryphal":       "canonical",
    "orthodox":         "heterodox",
    "heterodox":        "orthodox",
    "dogmatic":         "skeptical",
    "skeptical":        "dogmatic",
    "exoteric":         "esoteric",
    "esoteric":         "exoteric",
    "apodictic":        ["problematic", "assertoric"],
    "problematic":      "apodictic",
    "assertoric":       "apodictic",
    "a priori":         "a posteriori",
    "a posteriori":     "a priori",
    "analytic":         "synthetic",
    "synthetic":        "analytic",
    "categorical":      "hypothetical",
    "hypothetical":     "categorical",
    "deontic":          "alethic",
    "alethic":          "deontic",
    "heteronomous":     "autonomous",
    "autonomous":       "heteronomous",
    "disenchanted":     "enchanted",
    "enchanted":        "disenchanted",
    "monologic":        "dialogic",
    "dialogic":         "monologic",
    "centripetal":      "centrifugal",
    "centrifugal":      "centripetal",
    "homogeneous":      "heterogeneous",
    "heterogeneous":    "homogeneous",
    "colonial":         "postcolonial",
    "postcolonial":     "colonial",
    "metropolitan":     "peripheral",
    "peripheral":       "metropolitan",
    "etic":             "emic",
    "emic":             "etic"
        /* ================================================================
     *  Extensions: narratology, rhetoric, logic, modal logic,
     *  inferentialism, political science
     * ================================================================ */

    /* --- Narratology --- */
    "narrator":                "narratee",
    "narratee":                "narrator",
    "implied author":          "implied reader",
    "implied reader":          "implied author",
    "heterodiegetic":          "homodiegetic",
    "homodiegetic":            "heterodiegetic",
    "extradiegetic":           "intradiegetic",
    "intradiegetic":           "extradiegetic",
    "autodiegetic":            "heterodiegetic",
    "reliable":                "unreliable",
    "unreliable":              "reliable",
    "omniscient":              "limited",
    "limited":                 "omniscient",
    "showing":                 "telling",
    "telling":                 "showing",
    "story time":              "discourse time",
    "discourse time":          "story time",
    "frame":                   "embedded",
    "embedded":                "frame",
    "singular":                "iterative",
    "iterative":               "singular",
    "protagonist":             "antagonist",
    "antagonist":              "protagonist",
    "linear":                  "nonlinear",
    "nonlinear":               "linear",
    "diegetic":                "nondiegetic",
    "nondiegetic":             "diegetic",
    "story":                   ["plot", "discourse"],
    "discourse":               "story",
    "order":                   "duration",
    "duration":                "order",
    "mood":                    "voice",
    "voice":                   "mood",

    /* --- Rhetoric --- */
    "enthymeme":               "syllogism",
    "syllogism":               "enthymeme",
    "example":                 "enthymeme",
    "ethos":                   "pathos",
    "pathos":                  "ethos",
    "invention":               "arrangement",
    "arrangement":             "invention",
    "style":                   "delivery",
    "delivery":                "style",
    "memory":                  "delivery",
    "forensic":                "deliberative",
    "deliberative":            "forensic",
    "epideictic":              ["forensic", "deliberative"],
    "amplification":           "attenuation",
    "attenuation":             "amplification",
    "auxesis":                 "meiosis",
    "meiosis":                 "auxesis",
    "exordium":                "peroration",
    "peroration":              "exordium",
    "narratio":                "argumentatio",
    "argumentatio":            "narratio",
    "confirmatio":             "refutatio",
    "refutatio":               "confirmatio",
    "thesis":                  ["hypothesis", "antithesis"],
    "hypothesis":              "thesis",
    "antithesis":              "thesis",
    "dialectic":               "rhetoric",
    "rhetoric":                "dialectic",
    "persuasion":              "dissuasion",
    "dissuasion":              "persuasion",
    "kairos":                  "chronos",
    "chronos":                 "kairos",
    "decorum":                 "indecorum",
    "indecorum":               "decorum",
    "copia":                   "brevitas",
    "brevitas":                "copia",
    "encomium":                "invective",
    "invective":               "encomium",
    "panegyric":               "polemic",
    "polemic":                 "panegyric",
    "laudatio":                "vituperatio",
    "vituperatio":             "laudatio",
    "proposition":             "assumption",
    "assumption":              "proposition",
    "antecedent":              "consequent",
    "consequent":              "antecedent",
    "topic":                   "comment",
    "comment":                 "topic",
    "subject":                 ["object", "predicate"],
    "predicate":               "subject",

    /* --- Logic: joins, unions, and structural relations --- */
    "union":                   ["intersection", "disjunction"],
    "intersection":            "union",
    "join":                    "meet",
    "meet":                    "join",
    "supremum":                "infimum",
    "infimum":                 "supremum",
    "least upper bound":       "greatest lower bound",
    "greatest lower bound":    "least upper bound",
    "inclusive or":            "exclusive or",
    "exclusive or":            "inclusive or",
    "universal":               "existential",
    "existential":             "universal",
    "sound":                   "complete",
    "complete":                "sound",
    "proof":                   "model",
    "model":                   "proof",
    "provable":                "true",
    "true":                    "provable",
    "recursive":               "recursively enumerable",
    "recursively enumerable":  "recursive",
    "countable":               "uncountable",
    "uncountable":             "countable",
    "dense":                   "discrete",
    "discrete":                ["continuous", "dense"],
    "open":                    "closed",
    "closed":                  "open",
    "connected":               "disconnected",
    "disconnected":            "connected",
    "reflexive":               "irreflexive",
    "irreflexive":             "reflexive",
    "symmetric":               "asymmetric",
    "asymmetric":              "symmetric",
    "transitive":              "intransitive",
    "intransitive":            "transitive",
    "total":                   "partial",
    "partial":                 "total",
    "well-founded":            "ill-founded",
    "ill-founded":             "well-founded",
    "monotonic":               "nonmonotonic",
    "nonmonotonic":            "monotonic",
    "classical":               ["nonclassical", "intuitionistic"],
    "nonclassical":            "classical",
    "intuitionistic":          "classical",
    "paraconsistent":          "consistent",
    "consistent":              "paraconsistent",
    "many-valued":             "two-valued",
    "two-valued":              "many-valued",
    "bivalent":                "trivalent",
    "trivalent":               "bivalent",
    "fuzzy":                   "crisp",
    "crisp":                   "fuzzy",
    "modal":                   "assertoric",
    "de re":                   "de dicto",
    "de dicto":                "de re",
    "extensional":             "intensional",
    "intensional":             "extensional",
    "distributive":            "collective",
    "collective":              "distributive",
    "mereological":            "set-theoretic",
    "set-theoretic":           "mereological",
    "reductionist":            "emergentist",
    "emergentist":             "reductionist",
    "object language":         "metalanguage",
    "metalanguage":            "object language",
    "use":                     "mention",
    "mention":                 "use",
    "operator":                "operand",
    "operand":                 "operator",
    "free variable":           "bound variable",
    "bound variable":          "free variable",
    "satisfiable":             "unsatisfiable",
    "unsatisfiable":           "satisfiable",
    "first-order":             "higher-order",
    "higher-order":            "first-order",
    "monadic":                 "dyadic",
    "dyadic":                  "monadic",
    "unary":                   "binary",
    "binary":                  "unary",
    "sentence":                "term",
    "term":                    "sentence",
    "consequence":             "derivability",
    "derivability":            "consequence",
    "implication":             "implicature",
    "implicature":             "implication",
    "truth":                   ["falsity", "validity"],
    "validity":                "truth",

    /* --- Modal logic --- */
    "actual":                  "possible",
    "possible":                ["impossible", "actual"],
    "necessary":               ["contingent", "actual"],
    "alethic":                 "epistemic",
    "epistemic":               "alethic",
    "deontic":                 ["alethic", "epistemic"],
    "obligatory":              ["permitted", "forbidden"],
    "permitted":               ["obligatory", "forbidden"],
    "forbidden":               "obligatory",
    "knowing":                 "believing",
    "believing":               "knowing",
    "justified":               "unjustified",
    "unjustified":             "justified",
    "deterministic":           "indeterministic",
    "indeterministic":         "deterministic",
    "nomological":             "accidental",
    "accidental":              "nomological",
    "assertoric":              ["apodictic", "problematic"],
    "problematic":             "assertoric",
    "realis":                  "irrealis",
    "irrealis":                "realis",
    "indicative":              "subjunctive",
    "subjunctive":             "indicative",
    "counterfactual":          "factual",
    "factual":                 "counterfactual",
    "rigid":                   "descriptive",
    "descriptive":             "rigid",
    "possibility":             "actuality",
    "actuality":               "possibility",
    "contingency":             "impossibility",
    "impossibility":           "contingency",
    "imperative":              "declarative",
    "declarative":             ["imperative", "interrogative"],
    "interrogative":           "declarative",
    "bouletic":                "deontic",
    "doxastic":                "epistemic",
    "knowledge":               ["ignorance", "belief"],
    "belief":                  ["doubt", "knowledge"],

    /* --- Inferentialism (Brandom) --- */
    "inferentialism":          "representationalism",
    "representationalism":     "inferentialism",
    "referentialism":          "inferentialism",
    "inferential":             ["referential", "representational"],
    "referential":             "inferential",
    "representational":        "inferential",
    "normative":               ["descriptive", "naturalistic"],
    "descriptive":             ["rigid", "normative"],
    "naturalistic":            "normative",
    "scorekeeping":            "describing",
    "describing":              "scorekeeping",
    "commitment":              "entitlement",
    "entitlement":             ["commitment", "incapacity", "authorization"],
    "incapacity":              "entitlement",
    "authorization":           "entitlement",
    "discursive":              "practical",
    "practical":               "discursive",
    "sapience":                "sentience",
    "sentience":               "sapience",
    "sapient":                 "sentient",
    "sentient":                "sapient",
    "conceptual":              ["nonconceptual", "perceptual"],
    "nonconceptual":           "conceptual",
    "perceptual":              "conceptual",
    "space of reasons":        "space of causes",
    "space of causes":         "space of reasons",
    "normative status":        "normative attitude",
    "normative attitude":      "normative status",
    "thick":                   "thin",
    "thin":                    "thick",
    "sentential":              "subsentential",
    "subsentential":           "sentential",
    "pragmatic":               "semantic",
    "semantic":                "pragmatic",
    "pragmatism":              "platonism",
    "platonism":               "pragmatism",
    "community":               ["individual", "world"],
    "world":                   ["self", "community"],
    "recognition":             "reification",
    "reification":             "recognition",
    "recognitive":             ["objective", "cognitive"],
    "objective":               ["subjective", "recognitive"],
    "cognitive":               "recognitive",
    "I-Thou":                  "I-It",
    "I-It":                    "I-Thou",

    /* --- Political science --- */
    "democracy":               ["autocracy", "authoritarianism", "tyranny"],
    "autocracy":               "democracy",
    "authoritarianism":        "democracy",
    "tyranny":                 "democracy",
    "monarchy":                "republic",
    "republic":                "monarchy",
    "aristocracy":             "oligarchy",
    "oligarchy":               "aristocracy",
    "theocracy":               "secularism",
    "secularism":              "theocracy",
    "liberalism":              "conservatism",
    "conservatism":            "liberalism",
    "fascism":                 "communism",
    "communism":               "fascism",
    "anarchism":               "statism",
    "statism":                 "anarchism",
    "libertarianism":          "statism",
    "moderate":                ["radical", "extremist"],
    "extremist":               "moderate",
    "reform":                  ["revolution", "reaction"],
    "revolution":              "reform",
    "reaction":                "reform",
    "participatory":           "representative",
    "representative":          "participatory",
    "presidential":            "parliamentary",
    "parliamentary":           "presidential",
    "centralized":             "decentralized",
    "decentralized":           "centralized",
    "centralization":          "devolution",
    "devolution":              "centralization",
    "citizen":                 "alien",
    "alien":                   "citizen",
    "national":                ["international", "transnational"],
    "international":           "national",
    "transnational":           "national",
    "domestic":                "foreign",
    "foreign":                 ["native", "domestic"],
    "isolationism":            "interventionism",
    "interventionism":         "isolationism",
    "unilateralism":           "multilateralism",
    "multilateralism":         "unilateralism",
    "secular":                 ["holy", "theocratic"],
    "theocratic":              "secular",
    "state":                   ["market", "civil society"],
    "civil society":           "state",
    "civil":                   ["military", "martial"],
    "military":                "civil",
    "martial":                 "civil",
    "legislative":             ["executive", "judicial"],
    "executive":               ["legislative", "judicial"],
    "judicial":                ["legislative", "executive"],
    "demos":                   "ethnos",
    "ethnos":                  "demos",
    "egalitarian":             "hierarchical",
    "hierarchical":            "egalitarian",
    "pluralism":               "monism",
    "monism":                  "pluralism",
    "cosmopolitan":            ["nationalist", "patriotic"],
    "patriotic":               "cosmopolitan",
    "traitorous":              "patriotic",
    "loyal":                   ["subversive", "dissident"],
    "subversive":              "loyal",
    "dissident":               "loyal",
    "orthodox":                ["heterodox", "revisionist"],
    "revisionist":             "orthodox",
    "hawk":                    "dove",
    "dove":                    "hawk",
    "hawkish":                 "dovish",
    "dovish":                  "hawkish",
    "protectionist":           "free-trader",
    "free-trader":             "protectionist",
    "core":                    "periphery",
    "periphery":               "core",
    "metropole":               ["colony", "periphery"],
    "intergovernmental":       "supranational",
    "supranational":           "intergovernmental",
    "majoritarian":            ["proportional", "consociational"],
    "proportional":            "majoritarian",
    "consociational":          "majoritarian",
    "adversarial":             "consensual",
    "consensual":              "adversarial",
    "partisan":                ["bipartisan", "nonpartisan"],
    "bipartisan":              "partisan",
    "nonpartisan":             "partisan",
    "trustee":                 "delegate",
    "delegate":                "trustee",
    "Burkean":                 "plebiscitary",
    "plebiscitary":            "Burkean",
    "constitutional":          "unconstitutional",
    "unconstitutional":        "constitutional",
    "democratic":              ["oligarchic", "undemocratic"],
    "undemocratic":            "democratic",
    "accountable":             "unaccountable",
    "unaccountable":           "accountable",
    "nationalism":             "globalism",
    "globalism":               "nationalism",
    "civic":                   "ethnic",
    "ethnic":                  "civic",
    "liberal":                 "illiberal",
    "illiberal":               "liberal",
    "republican":              "monarchical",
    "monarchical":             "republican"
};

