/* INVESTMENTS: 955 entries */
var INVESTMENTS = {
    "just": ["inequitable", "unfair", "unjust"],
    "like": ["alike", "different", "disapproval", "disfavor", "disfavour", "dislike", "dissimilar", "likewise", "similar", "unlike"],
    "make": ["undo", "unmake"],
    "back": "aback",
    "well": ["ailing", "indisposed", "peaked", "poorly", "seedy", "sickly", "under the weather", "unwell"],
    "said": ["swallow", "take back", "unexpressed", "unsaid", "unsay", "unspoken", "unstated", "unuttered", "unverbalised", "unverbalized", "unvoiced", "withdraw"],
    "most": ["inmost", "innermost"],
    "even": ["mismatched", "odd", "scratchy", "spotty", "uneven"],
    "here": "inhere",
    "need": ["gratuitous", "uncalled-for"],
    "right": ["aright", "correctly"],
    "being": "nonbeing",
    "made": ["undo", "unmade", "unmake"],
    "still": ["impregnate", "impress", "inculcate", "infuse", "ingrain", "instil", "instill", "tincture", "transfuse"],
    "take": ["aspiration", "breathing in", "consumption", "ingestion", "inhalation", "inlet", "inspiration", "intake", "uptake"],
    "got": ["block of metal", "ingot", "metal bar"],
    "life": "exanimate",
    "while": ["awhile", "for a while"],
    "such": ["apotheosis", "ideal", "nonesuch", "nonpareil", "nonsuch", "paragon", "saint"],
    "man": "unman",
    "home": ["dispossessed", "homeless person"],
    "long": "along",
    "used": ["disused", "fresh", "idle", "obsolete", "unused"],
    "come": "income",
    "part": ["add", "apart", "aside", "asunder", "bestow", "bring", "carry", "channel", "conduct", "contribute", "convey", "give", "impart", "isolated", "leave", "lend", "obscure", "pass on", "transmit"],
    "between": ["mediate", "middle"],
    "better": ["abetter", "abettor"],
    "help": ["incapacitated", "lost"],
    "own": ["disinherit", "disown", "renounce", "repudiate"],
    "place": ["can", "dismiss", "displace", "fire", "force out", "give notice", "give the axe", "give the sack", "move", "preempt", "sack", "send away", "terminate"],
    "end": ["eternal", "interminable", "sempiternal"],
    "sure": ["ascertain", "assure", "check", "control", "cover", "diffident", "ensure", "guarantee", "incertain", "insure", "secure", "see", "see to it", "shy", "timid", "uncertain", "underwrite", "unsure"],
    "team": "a-team",
    "please": "displease",
    "free": "unfree",
    "number": ["infinite", "innumerable", "innumerous", "multitudinous", "myriad", "uncounted", "unnumberable", "unnumbered", "unnumerable"],
    "name": ["unidentified", "unknown", "unnamed"],
    "play": ["display", "exhibit", "expose", "presentation", "show", "showing", "video display"],
    "doing": ["loosen", "undo", "undoing", "unfastening", "unmake", "untie", "untying", "unwrap"],
    "real": ["areal", "artificial", "insubstantial", "unreal", "unsubstantial"],
    "different": ["apathetic", "deaf", "immaterial", "indifferent", "inert", "neutral", "so-so", "unbiased", "unbiassed"],
    "set": ["gusset", "insert", "inset"],
    "thought": ["uncaring", "unhoped", "unhoped-for", "unthinking", "unthought", "unthought-of"],
    "done": ["done for", "loosen", "ruined", "sunk", "undo", "undone", "unmake", "unstuck", "untie", "unwrap", "washed-up"],
    "god": "irreverent",
    "group": ["camp", "clique", "coterie", "ingroup", "inner circle", "pack"],
    "public": "nonpublic",
    "top": ["atop", "bare-breasted"],
    "case": ["discase", "disrobe", "encase", "incase", "peel", "strip", "strip down", "uncase", "unclothe", "undress"],
    "person": ["in the flesh", "nonperson", "unperson"],
    "change": ["constant", "immutable", "invariant", "unalterable", "unvarying"],
    "live": ["active", "alert", "alive", "animated", "awake", "live down", "unlive"],
    "point": ["otiose", "superfluous", "unpointed", "wasted"],
    "read": "unread",
    "told": "untold",
    "seen": ["spiritual domain", "spiritual world", "unobserved", "unseen"],
    "stop": ["around-the-clock", "day-and-night", "nonstop", "nonstop flight", "round-the-clock"],
    "water": "arid",
    "believe": ["disbelieve", "discredit"],
    "head": ["ahead", "before", "beforehand", "forrader", "forward", "forwards", "in advance", "in front", "in the lead", "leading", "onward", "onwards", "out front"],
    "men": ["amen", "amon", "amun", "ilmen", "lake ilmen"],
    "white": ["colored", "coloured", "dark", "dark-skinned"],
    "far": "afar",
    "job": ["idle", "out of work"],
    "side": ["apart", "aside", "at bottom", "at heart", "away", "deep down", "digression", "divagation", "excursus", "in spite of appearance", "indoors", "inner", "inside", "interior", "inwardly", "parenthesis", "privileged", "within"],
    "line": ["a-line", "adjust", "align", "aline", "line up"],
    "order": ["cark", "disarray", "disorder", "disorderliness", "disquiet", "distract", "perturb", "trouble", "unhinge", "upset"],
    "service": ["disservice", "ill service", "ill turn"],
    "open": ["closed", "shut", "unopen"],
    "thank": ["unappreciated", "ungrateful", "ungratifying", "unthankful"],
    "united": ["disassociate", "disconnected", "disjoint", "dissociate", "disunite", "disunited", "divide", "divorce", "fragmented", "part", "separate", "split"],
    "black": ["antiblack", "racist"],
    "law": ["anarchic", "anarchical", "outlaw", "relative-in-law", "wide-open"],
    "kind": "unkind",
    "per": ["ape", "aper", "copycat", "emulator", "imitator"],
    "course": ["converse", "discourse", "discuss", "discussion", "dissertate", "hold forth", "preaching", "sermon", "talk about", "treatment"],
    "important": ["insignificant", "unimportant"],
    "able": ["disable", "disenable", "handicap", "incapacitate", "ineffective", "ineffectual", "invalid", "unable"],
    "information": "disinformation",
    "post": ["custom", "customs", "customs duty", "impost", "springer"],
    "ago": "imago",
    "social": ["antisocial", "asocial", "nongregarious", "nonsocial", "solitary", "unsocial"],
    "hand": ["bumbling", "bungling", "butterfingered", "ham-fisted", "ham-handed", "heavy-handed", "left-handed", "unhand"],
    "mind": ["asinine", "fatuous", "forgetful", "inane", "unmindful", "vacuous"],
    "body": ["antibody", "discorporate", "disembodied", "unbodied", "unembodied"],
    "coming": ["entering", "entrance", "entry", "incoming", "ingress"],
    "death": "undying",
    "true": ["false", "out of true", "untrue"],
    "known": ["alien", "obscure", "strange", "stranger", "terra incognita", "unidentified", "unknown", "unknown quantity", "unknown region", "unnamed", "unsung"],
    "matter": "antimatter",
    "air": ["close", "stuffy", "unaired"],
    "friend": "outcast",
    "probably": ["implausibly", "improbably", "incredibly", "unbelievably"],
    "class": "egalitarian",
    "close": ["break", "bring out", "close in", "disclose", "discover", "divulge", "enclose", "expose", "give away", "inclose", "insert", "introduce", "let on", "let out", "put in", "reveal", "shut in", "stick in", "unwrap"],
    "possible": ["impossible", "inconceivable", "insufferable", "out of the question", "unacceptable", "unimaginable", "unsufferable"],
    "wanted": ["undesirable", "unwanted"],
    "cause": ["fortuitous", "uncaused"],
    "due": ["empower", "endow", "endue", "excessive", "gift", "indue", "inordinate", "invest", "undue", "unjustified", "unreasonable", "unwarranted"],
    "happy": ["distressed", "dysphoric", "infelicitous", "unhappy"],
    "human": ["cold", "cold-blooded", "dehumanised", "dehumanized", "inhuman", "insensate", "nonhuman", "unhuman"],
    "wait": ["await", "expect", "look"],
    "late": ["alate", "alated"],
    "light": ["ablaze", "afire", "aflame", "aflare", "alight", "climb down", "on fire", "perch", "unilluminated", "unlighted", "unlit"],
    "age": ["aeonian", "double", "effigy", "envision", "eonian", "epitome", "eternal", "everlasting", "fancy", "figure", "figure of speech", "icon", "ikon", "image", "look-alike", "mental image", "minority", "nonage", "paradigm", "perpetual", "persona", "picture", "project", "prototype", "range", "range of a function", "see", "simulacrum", "trope", "unceasing", "unending", "visualise", "visualize"],
    "reason": ["irrationality", "unreason"],
    "development": "nondevelopment",
    "form": ["amorphous", "inform"],
    "heart": "hardhearted",
    "asked": ["unasked", "unsolicited"],
    "fire": ["ablaze", "afire", "aflame", "aflare", "alight", "on fire"],
    "living": ["inanimate", "nonliving"],
    "art": ["ingenuous", "uncultivated", "uncultured"],
    "easy": ["anxious", "awkward", "ill at ease", "nervous", "queasy", "uneasy", "unquiet"],
    "non": "anon",
    "plan": ["adrift", "afloat", "undirected"],
    "political": ["apolitical", "nonpolitical", "unpolitical"],
    "available": "unavailable",
    "former": ["betrayer", "blabber", "informer", "rat", "squealer"],
    "list": ["a-list", "dispirited"],
    "ready": "unready",
    "current": "noncurrent",
    "experience": ["inexperience", "rawness"],
    "heard": "unheard",
    "type": "antitype",
    "word": ["mute", "unspoken"],
    "action": ["inaction", "inactiveness", "inactivity"],
    "clear": ["ill-defined", "indecipherable", "unclear", "undecipherable", "unreadable"],
    "gave": ["agave", "american aloe", "century plant"],
    "self": "altruistic",
    "board": ["aboard", "alongside", "inboard", "on base", "on board"],
    "cost": ["complimentary", "free", "gratis", "gratuitous"],
    "cut": ["full-length", "rough", "uncut", "unmown", "untrimmed"],
    "field": ["abroad", "afield", "baseball diamond", "diamond", "infield"],
    "main": "amain",
    "road": ["inroad", "untracked", "untrod", "untrodden"],
    "thinking": ["lumpen", "lumpish", "uncaring", "unreflective", "unthinking", "unthinkingly", "unthoughtful"],
    "force": "unforceful",
    "issue": "dead letter",
    "price": "invaluable",
    "rest": ["agitation", "ferment", "fermentation", "tempestuousness", "uneasy", "ungratified", "unrest", "unsatisfied"],
    "date": ["sempiternal", "undated"],
    "land": "inland",
    "miss": ["amiss", "awry", "brush aside", "brush off", "can", "discount", "dismiss", "displace", "disregard", "dissolve", "drop", "fire", "force out", "give notice", "give the axe", "give the sack", "haywire", "ignore", "imperfectly", "push aside", "sack", "send away", "send packing", "terminate", "throw out", "usher out", "wrong"],
    "sex": ["desex", "desexualise", "desexualize", "fix", "neuter", "sterilise", "sterilize", "unsex"],
    "position": ["disposal", "disposition", "imposition", "inclination", "infliction", "temperament", "tendency"],
    "similar": ["different", "dissimilar", "unalike", "unlike"],
    "common": ["rare", "uncommon"],
    "lead": "unleaded",
    "likely": ["improbable", "unbelievable", "unconvincing", "unlikely"],
    "military": ["nonmilitary", "unmilitary"],
    "perfect": ["continuous tense", "fallible", "frail", "imperfect", "imperfect tense", "progressive", "progressive tense", "weak"],
    "personal": ["impersonal", "neutral", "nonpersonal"],
    "security": "insecurity",
    "county": ["infinite", "innumerable", "innumerous", "multitudinous", "myriad", "uncounted", "unnumberable", "unnumbered", "unnumerable"],
    "couple": ["decouple", "uncouple"],
    "sense": ["bunk", "falderol", "folderal", "frill", "gimcrack", "gimcrackery", "hokum", "insensible", "meaninglessness", "nitwitted", "nonsense", "nonsensical", "nonsensicality", "otiose", "soft-witted", "superfluous", "trumpery", "wasted"],
    "star": "instar",
    "event": "nonevent",
    "member": ["discerp", "dismember", "nonmember", "take apart"],
    "needed": ["unnecessary", "unneeded"],
    "gone": ["ago", "agone", "antigone"],
    "interest": ["disinterest", "neutrality"],
    "learn": "unlearn",
    "certain": ["changeable", "incertain", "uncertain", "unsealed", "unsettled", "unsure"],
    "church": ["curse", "excommunicate", "unchurch"],
    "medical": ["nonmedicinal", "unmedical", "unmedicative", "unmedicinal"],
    "original": "unoriginal",
    "performance": ["carelessness", "neglect", "negligence", "nonperformance"],
    "press": ["affect", "impress", "impressment", "imprint", "ingrain", "instill", "move", "print", "shanghai", "strike", "yarn-dye"],
    "sent": ["differ", "disagree", "dissent", "objection", "protest", "resist", "take issue", "unsent"],
    "tried": ["unseasoned", "untested", "untried", "young"],
    "worth": ["despicable", "slimy", "ugly", "unworthy", "vile", "wretched"],
    "cool": "uncool",
    "exactly": ["imprecisely", "inexactly"],
    "ground": ["aground", "idle", "unfounded", "unwarranted", "wild"],
    "sound": ["bad", "fallacious", "mentally ill", "silent", "still", "unfit", "unsound", "unstable"],
    "usually": ["outstandingly", "remarkably", "unco", "unusually"],
    "official": "unofficial",
    "round": ["about", "approximately", "around", "close to", "just about", "or so", "roughly", "some"],
    "stuff": ["loosen up", "unstuff"],
    "feeling": ["hardhearted", "stonyhearted", "unfeeling"],
    "match": ["nonpareil", "one", "one and only", "unmatchable", "unmatched", "unrivaled", "unrivalled"],
    "step": "instep",
    "trust": ["antimonopoly", "antitrust", "commit", "confide", "distrust", "distrustfulness", "entrust", "intrust", "misgiving", "mistrust", "suspect", "suspicion"],
    "paid": ["amateur", "recreational", "unpaid", "volunteer"],
    "trade": ["antitrade", "antitrade wind"],
    "attention": "inattention",
    "character": "nondescript",
    "natural": ["abnormal", "affected", "nonnatural", "otherworldly", "preternatural", "transcendental", "unnatural"],
    "property": ["blue-collar", "wage-earning", "working-class"],
    "style": "unstylish",
    "vote": ["disenfranchised", "disfranchised"],
    "blood": ["ashen", "blanched", "exsanguine", "exsanguinous", "livid", "white"],
    "complete": ["incomplete", "uncomplete", "uncompleted"],
    "economic": ["uneconomic", "uneconomical"],
    "involved": ["degage", "detached", "uninvolved"],
    "related": "unrelated",
    "born": ["congenital", "connatural", "inborn", "inbred", "innate", "unborn"],
    "decided": ["on the fence", "open", "undecided", "undetermined", "unresolved"],
    "decision": ["indecision", "indecisiveness", "irresolution"],
    "turned": "unturned",
    "written": ["ad-lib", "oral", "spontaneous", "unwritten"],
    "considered": ["inconsiderate", "unconsidered"],
    "continue": ["break", "break off", "cease", "discontinue", "give up", "lay off", "quit", "stop"],
    "cover": ["attain", "break", "bring out", "chance on", "chance upon", "come across", "come upon", "describe", "detect", "disclose", "discover", "distinguish", "divulge", "expose", "fall upon", "find", "find out", "get a line", "get wind", "get word", "give away", "happen upon", "hear", "identify", "key", "key out", "learn", "let on", "let out", "light upon", "name", "notice", "observe", "pick up", "reveal", "see", "strike", "uncover", "unveil", "unwrap"],
    "door": "indoor",
    "financial": "nonfinancial",
    "legal": ["extralegal", "illegal", "nonlegal"],
    "pick": ["unknot", "unpick", "unravel", "unscramble", "untangle"],
    "union": ["disunion", "nonunion"],
    "bed": ["abed", "embed", "engraft", "imbed", "implant", "plant"],
    "built": ["built-in", "constitutional", "inbuilt", "inherent", "integral"],
    "changed": ["unaltered", "unchanged"],
    "die": "indie",
    "figure": ["blemish", "deface", "disfigure"],
    "modern": "nonmodern",
    "popular": "unpopular",
    "published": "unpublished",
    "safe": ["dangerous", "insecure", "unsafe"],
    "version": ["anastrophe", "antipathy", "aversion", "averting", "distaste", "eversion", "everting", "inversion", "sexual inversion", "upending"],
    "voice": ["account", "aphonic", "bill", "breathed", "disenfranchised", "disfranchised", "hard", "invoice", "surd", "unvoiced"],
    "earth": ["excavate", "unearth"],
    "okay": ["a-ok", "a-okay"],
    "sea": ["asea", "seaward", "seawards"],
    "base": ["abase", "chagrin", "humble", "humiliate", "idle", "mortify", "unfounded", "unwarranted", "wild"],
    "professional": ["nonprofessional", "unprofessional"],
    "released": "unreleased",
    "risk": ["risk-free", "unhazardous"],
    "sleep": ["asleep", "at peace", "at rest", "benumbed", "deceased", "departed", "gone", "insomniac", "numb", "watchful"],
    "ten": ["aten", "aton"],
    "truth": ["falsehood", "falsity", "untruth"],
    "box": "unbox",
    "card": ["cast aside", "cast away", "cast out", "chuck out", "discard", "dispose", "fling", "put away", "throw away", "throw out", "throwing away", "toss", "toss away", "toss out"],
    "mine": ["amine", "aminoalkane"],
    "piece": ["apiece", "each", "for each one", "from each one", "to each one"],
    "seeing": ["unobservant", "unseeing"],
    "growth": "ingrowth",
    "married": ["single", "unmarried"],
    "respect": ["contempt", "discourtesy", "disesteem", "disrespect"],
    "specific": ["broad", "nonspecific", "unspecific"],
    "standard": "nonstandard",
    "charge": ["acquit", "arc", "assoil", "clear", "complete", "discharge", "dismissal", "dismission", "dispatch", "drop", "drop off", "eject", "electric arc", "electric discharge", "emission", "empty", "exculpate", "exhaust", "exonerate", "expel", "expelling", "fire", "firing", "firing off", "free", "go off", "liberation", "muster out", "outpouring", "put down", "release", "run", "sack", "sacking", "set down", "spark", "unload", "venting", "waiver"],
    "cold": "acold",
    "eye": "unseeing",
    "funny": "unfunny",
    "limited": ["inexhaustible", "outright", "straight-out", "unlimited"],
    "moving": ["nonmoving", "unmoving"],
    "spent": ["unexpended", "unspent"],
    "track": ["untracked", "untrod", "untrodden"],
    "allow": ["disallow", "forbid", "interdict", "nix", "prohibit", "proscribe", "veto"],
    "association": ["disassociation", "dissociation"],
    "difference": ["apathy", "emotionlessness", "impassiveness", "impassivity", "indifference", "nonchalance", "numbness", "phlegm", "spiritlessness", "stolidity", "unconcern", "unemotionality"],
    "moved": ["unaffected", "unmoved", "untouched"],
    "certainly": ["falteringly", "uncertainly", "unsteadily"],
    "completely": "incompletely",
    "content": ["discontent", "discontented", "discontentedness", "discontentment"],
    "credit": ["disbelieve", "discredit", "disgrace", "disrepute"],
    "cross": ["across", "crossways", "crosswise", "uncross"],
    "interesting": "uninteresting",
    "join": ["disjoin", "disjoint"],
    "kept": ["broken", "unkept"],
    "loved": "unloved",
    "reported": "unreported",
    "section": "dissection",
    "fair": ["unfair", "unjust"],
    "welcome": ["unwelcome", "unwished", "unwished-for"],
    "significant": ["insignificant", "nonsignificant", "peanut", "undistinguished", "unimportant"],
    "agree": ["differ", "disaccord", "disagree", "discord", "dissent", "take issue"],
    "clean": ["dirty", "impure", "soiled", "unclean"],
    "justice": ["iniquity", "injustice", "shabbiness", "unfairness", "unjustness"],
    "sold": "unsold",
    "sun": ["cloud-covered", "clouded", "overcast"],
    "ability": ["disability", "disablement", "handicap", "impairment", "inability", "unfitness"],
    "announced": ["unannounced", "unheralded", "unpredicted"],
    "continued": ["break", "break off", "cease", "discontinue", "discontinued", "give up", "lay off", "quit", "stop"],
    "definitely": "indefinitely",
    "designed": "undesigned",
    "expected": "unexpected",
    "train": "distrain",
    "claim": "disclaim",
    "dad": "adad",
    "developed": ["undeveloped", "unexploited"],
    "fear": ["audacious", "brave", "hardy", "intrepid", "unafraid", "unfearing"],
    "fit": ["bad", "disqualify", "indispose", "unfit", "unsound"],
    "german": ["inger", "ingerman", "ingrian"],
    "interested": ["disinterested", "uninterested"],
    "material": ["extraneous", "immaterial", "impertinent", "incorporeal", "indifferent", "nonmaterial", "orthogonal"],
    "named": ["unidentified", "unknown", "unnamed"],
    "plus": ["amaze", "baffle", "beat", "bewilder", "dumbfound", "flummox", "get", "gravel", "mystify", "nonplus", "perplex", "pose", "puzzle", "stick", "stupefy", "vex"],
    "regular": ["atypical", "guerilla", "guerrilla", "insurgent", "irregular", "maverick", "second", "temporary", "unorthodox", "unpredictable"],
    "bar": ["disbar", "unbar"],
    "finished": ["bare", "unfinished"],
    "growing": ["ingrowing", "ingrown"],
    "hurt": ["safe and sound", "unharmed", "unhurt", "unscathed", "whole"],
    "opening": "nonopening",
    "physical": ["intangible", "nonphysical"],
    "successful": ["abortive", "stillborn", "unsuccessful"],
    "active": ["dormant", "inactive", "nonoperational", "passive", "static", "still"],
    "cancer": ["anticancer", "antineoplastic", "antitumor", "antitumour"],
    "civil": ["rude", "uncivil"],
    "defense": "naked",
    "direction": ["adrift", "afloat", "indirection", "undirected"],
    "band": ["disband", "dissolve"],
    "clearly": "unclearly",
    "commercial": ["noncommercial", "uncommercial"],
    "effort": "casual",
    "ended": "unended",
    "organization": ["disarrangement", "disorganisation", "disorganization"],
    "color": ["colour", "discolor", "discolour"],
    "direct": ["collateral", "indirect"],
    "easily": ["anxiously", "apprehensively", "uneasily"],
    "luck": "unlucky",
    "marriage": ["endogamy", "inmarriage", "intermarriage"],
    "necessary": ["unnecessary", "unneeded"],
    "speaking": ["nonspeaking", "walk-on"],
    "sweet": ["nonsweet", "sec", "unsweet"],
    "closed": ["break", "bring out", "disclose", "disclosed", "discover", "divulge", "expose", "give away", "let on", "let out", "reveal", "unwrap"],
    "directly": "indirectly",
    "doubt": "undoubtedly",
    "established": "unestablished",
    "trip": ["atrip", "aweigh"],
    "basic": ["abasic", "abatic"],
    "effective": ["ineffective", "ineffectual", "inefficient", "unable", "uneffective"],
    "plant": ["embed", "engraft", "imbed", "implant"],
    "reality": ["irreality", "unreality"],
    "spot": ["immaculate", "spic", "spic-and-span", "spick", "spick-and-span"],
    "agreement": ["disagreement", "discrepancy", "dissension", "dissonance", "divergence", "variance"],
    "block": ["free", "release", "unblock", "unfreeze"],
    "broken": ["kept", "unbroken", "unploughed", "unplowed"],
    "caused": ["fortuitous", "uncaused"],
    "christian": ["nonchristian", "unchristian"],
    "holy": ["demonic", "diabolic", "diabolical", "fiendish", "hellish", "infernal", "satanic", "sinful", "unhallowed", "unholy", "wicked"],
    "purpose": ["otiose", "superfluous", "wasted"],
    "responsible": "irresponsible",
    "foot": ["afoot", "underway"],
    "mass": ["accumulate", "amass", "collect", "compile", "conglomerate", "cumulate", "gather", "hoard", "pile up", "roll up"],
    "meaning": "nonmeaningful",
    "mission": ["discharge", "dismissal", "dismission", "firing", "liberation", "pink slip", "release", "sack", "sacking"],
    "trial": "atrial",
    "truly": "untruly",
    "activity": ["inaction", "inactiveness", "inactivity", "inertia"],
    "located": ["disjointed", "dislocate", "dislocated", "luxate", "separated", "slip", "splay", "unlocated"],
    "location": ["breakdown", "dislocation", "disruption"],
    "appear": ["disappear", "evaporate", "go away", "melt", "vanish"],
    "fat": ["fat-free", "nonfat"],
    "glass": "unglazed",
    "learned": ["ignorant", "innate", "nescient", "unconditioned", "unlearn", "unlearned", "unlettered"],
    "mobile": ["fast", "firm", "immobile"],
    "opened": "unopened",
    "placed": "unplaced",
    "reached": ["out of reach", "unapproachable", "unreachable", "unreached"],
    "religious": "irreligious",
    "signed": "unsigned",
    "speech": "dumb",
    "tree": "unwooded",
    "famous": ["ill-famed", "infamous", "notorious"],
    "investment": "disinvestment",
    "raised": ["unleavened", "unraised"],
    "solution": ["adjournment", "breakup", "disintegration", "dissipation", "dissolution", "dissolving", "licentiousness", "looseness", "profligacy"],
    "traditional": ["nontraditional", "untraditional"],
    "wind": ["decompress", "disentangle", "loosen up", "make relaxed", "relax", "slow down", "unbend", "unlax", "unroll", "unstrain", "unwind", "wind off"],
    "count": ["bank discount", "brush aside", "brush off", "deduction", "discount", "discount rate", "dismiss", "disregard", "ignore", "infinite", "innumerable", "innumerous", "multitudinous", "myriad", "price reduction", "push aside", "rebate", "uncounted", "unnumberable", "unnumbered", "unnumerable"],
    "covered": ["ascertained", "attain", "break", "bring out", "chance on", "chance upon", "come across", "come upon", "describe", "detect", "disclose", "discover", "discovered", "distinguish", "divulge", "expose", "exposed", "fall upon", "find", "find out", "get a line", "get wind", "get word", "give away", "happen upon", "hear", "identify", "key", "key out", "learn", "let on", "let out", "light upon", "name", "notice", "observe", "observed", "pick up", "reveal", "see", "strike", "uncover", "uncovered", "unveil", "unwrap"],
    "critical": ["acritical", "noncritical", "noncrucial", "uncritical"],
    "forced": ["uncoerced", "unforced", "unstrained", "willing"],
    "fresh": ["afresh", "anew"],
    "missed": ["brush aside", "brush off", "can", "discharged", "discount", "dismiss", "dismissed", "displace", "disregard", "dissolve", "drop", "fire", "fired", "force out", "give notice", "give the axe", "give the sack", "ignore", "laid-off", "pink-slipped", "push aside", "sack", "send away", "send packing", "terminate", "throw out", "usher out"],
    "mouth": "astomatous",
    "owner": "unowned",
    "tom": ["atom", "corpuscle", "molecule", "mote", "particle", "speck"],
    "faith": ["traitorous", "treasonable", "treasonous", "unfaithful"],
    "hearing": ["deaf as a post", "profoundly deaf", "stone-deaf", "unhearing"],
    "metal": ["nonmetal", "nonmetallic"],
    "seat": "unseat",
    "sexual": ["asexual", "nonsexual"],
    "becoming": ["indecent", "indecorous", "unbecoming", "uncomely", "unseemly", "untoward"],
    "gain": ["again", "once again", "once more", "over again"],
    "rise": ["arise", "bob up", "come up", "develop", "get up", "go up", "grow", "lift", "move up", "originate", "rebel", "rise up", "spring up", "stand up", "turn out", "uprise"],
    "healthy": ["insalubrious", "unhealthful", "unhealthy"],
    "prison": ["gaol", "immure", "imprison", "incarcerate", "jail", "jug", "lag", "put away", "put behind bars", "remand"],
    "bet": "abet",
    "christ": ["antichrist", "nonchristian"],
    "correct": ["faulty", "incorrect", "wrong"],
    "firm": ["debile", "decrepit", "feeble", "infirm", "rickety", "shifting", "unfirm", "unsteady", "weak", "weakly"],
    "negative": "nonnegative",
    "spirit": ["inspirit", "meek", "spirit up"],
    "till": ["condense", "distil", "distill", "extract", "make pure", "purify", "sublimate"],
    "advantage": ["disadvantage", "disfavor", "disfavour"],
    "aware": ["incognizant", "unaware"],
    "function": ["disfunction", "dysfunction"],
    "bridge": ["abbreviate", "abridge", "contract", "cut", "foreshorten", "reduce", "shorten"],
    "completed": ["incomplete", "uncompleted"],
    "lucky": ["doomed", "ill-fated", "ill-omened", "ill-starred", "unlucky"],
    "patient": ["impatient", "inmate", "inpatient", "raring"],
    "possibly": "impossibly",
    "prove": ["ameliorate", "amend", "better", "confute", "disprove", "improve", "meliorate"],
    "balance": ["asymmetry", "derange", "derangement", "dissymmetry", "imbalance", "instability", "mental unsoundness", "unbalance"],
    "changing": ["stable", "static", "unchanging"],
    "connection": ["disconnect", "disconnectedness", "disconnection", "disjunction", "disjuncture", "gulf"],
    "dress": ["discase", "disinvest", "disrobe", "divest", "peel", "strip", "strip down", "uncase", "unclothe", "undress"],
    "horse": ["ahorse", "ahorseback", "dismount", "get down", "get off", "horseback", "light", "unhorse"],
    "knowing": ["ignorant", "ignorantness", "nescience", "unknowing", "unknowingness", "unknowledgeable", "unwitting"],
    "liked": ["dislike", "disliked"],
    "owned": "unowned",
    "stick": "nonstick",
    "wake": ["alert", "alive", "arouse", "awake", "awaken", "come alive", "heavy", "profound", "sound", "wake up", "waken"],
    "concerned": "unconcerned",
    "driver": "nondriver",
    "fix": ["enter", "infix", "insert", "introduce"],
    "responsibility": ["irresponsibility", "irresponsibleness"],
    "roll": ["unfurl", "unroll", "unwind", "wind off"],
    "technical": ["nontechnical", "untechnical"],
    "violence": ["nonviolence", "nonviolent resistance", "passive resistance"],
    "discovered": ["undiscovered", "unexplored"],
    "excited": "unexcited",
    "lovely": ["unlovely", "unpicturesque"],
    "ordered": ["broken", "cark", "confused", "disarray", "disconnected", "disjointed", "disorder", "disordered", "disquiet", "distract", "garbled", "illogical", "perturb", "scattered", "trouble", "unconnected", "ungraded", "unhinge", "unordered", "unranked", "upset"],
    "prepared": "unprepared",
    "religion": ["irreligion", "irreligiousness"],
    "stated": ["unexpressed", "unsaid", "unspoken", "unstated", "unuttered", "unverbalised", "unverbalized", "unvoiced"],
    "arm": ["demilitarise", "demilitarize", "disarm", "unarm"],
    "democratic": "undemocratic",
    "honest": ["bribable", "corruptible", "dishonest", "dishonorable", "purchasable", "venal"],
    "joined": ["disjoin", "disjoined", "disjoint", "separate"],
    "lee": "alee",
    "port": ["amuse", "cavort", "consequence", "disport", "divert", "frisk", "frolic", "gambol", "implication", "import", "importation", "importee", "lark", "lark about", "meaning", "moment", "rollick", "romp", "run around", "significance", "signification", "skylark", "spell", "sport"],
    "taste": ["antipathy", "aversion", "distaste"],
    "pair": ["deflower", "impair", "mar", "spoil", "vitiate"],
    "proper": ["improper", "unconventional", "unlawful", "wrong"],
    "shape": "amorphous",
    "toward": ["adverse", "inauspicious", "indecent", "indecorous", "unbecoming", "uncomely", "unseemly", "untoward"],
    "willing": "unwilling",
    "capacity": "incapacity",
    "industrial": "nonindustrial",
    "joint": ["disarticulate", "disassociate", "disjoin", "disjoint", "dissociate", "disunite", "divorce"],
    "mix": ["blend", "coalesce", "combine", "commingle", "conflate", "flux", "fuse", "immix", "meld", "merge"],
    "path": ["untracked", "untrod", "untrodden"],
    "tired": ["untired", "unwearied", "unweary"],
    "treated": "untreated",
    "afraid": ["secure", "unafraid", "untroubled"],
    "filled": "unfilled",
    "fixed": ["nebulous", "unfixed"],
    "forest": ["deforest", "disafforest", "disforest"],
    "intended": "unintended",
    "limit": ["illimitable", "unbounded", "unlimited"],
    "profit": ["nonprofit", "nonprofit organization", "not-for-profit"],
    "proof": ["disproof", "falsification", "falsifying", "refutal", "refutation"],
    "appearance": ["disappearance", "disappearing", "fade", "nonappearance"],
    "domestic": "undomestic",
    "expensive": ["cheap", "inexpensive"],
    "historical": "ahistorical",
    "honestly": ["deceitfully", "dishonestly", "venally"],
    "honor": ["assault", "attaint", "disgrace", "dishonor", "dishonour", "outrage", "rape", "ravish", "shame", "violate"],
    "listed": "unlisted",
    "native": ["foreign-born", "nonnative"],
    "noted": ["overlooked", "unmarked", "unnoted"],
    "originally": "unoriginally",
    "planned": ["unintentional", "unplanned", "unwitting"],
    "combined": "uncombined",
    "connected": ["abrupt", "confused", "disconnect", "disconnected", "disjointed", "disordered", "disunited", "fragmented", "garbled", "illogical", "scattered", "split", "staccato", "unconnected", "unplug"],
    "ending": ["aeonian", "eonian", "eternal", "everlasting", "perpetual", "unceasing", "unending"],
    "flow": ["inflow", "influx"],
    "formed": ["inform", "informed", "unformed"],
    "hero": "antihero",
    "performed": "unperformed",
    "selected": "unselected",
    "shared": "unshared",
    "stuck": ["undone", "unstuck"],
    "sugar": "nonsweet",
    "supported": "unsupported",
    "surprised": ["not surprised", "unsurprised"],
    "taught": ["unschooled", "untaught", "unteach", "untutored"],
    "accepted": ["unacceptable", "unaccepted"],
    "appropriate": ["inappropriate", "incompatible", "out or keeping", "unfitting"],
    "confirmed": "unconfirmed",
    "grown": ["ingrowing", "ingrown"],
    "regarding": ["brush aside", "brush off", "cut", "discount", "dismiss", "disregard", "disregarding", "ignore", "irrespective", "neglect", "no matter", "push aside", "snub"],
    "saved": ["cursed", "damned", "doomed", "unredeemed", "unsaved"],
    "scientific": "unscientific",
    "teach": "unteach",
    "abuse": "disabuse",
    "angry": "unangry",
    "candidate": "noncandidate",
    "comfortable": "uncomfortable",
    "concern": ["indifference", "nonchalance", "unconcern"],
    "emotional": ["restrained", "reticent", "unemotional"],
    "liberal": ["illiberal", "intolerant"],
    "pack": ["take out", "unpack"],
    "payment": ["default", "evasion", "nonpayment", "nonremittal"],
    "recorded": ["live", "unrecorded"],
    "chain": "unchain",
    "committed": ["available", "unattached", "uncommitted"],
    "cute": ["acuate", "acute", "acute accent", "ague", "discriminating", "incisive", "intense", "keen", "knifelike", "needlelike", "penetrating", "penetrative", "piercing", "sharp"],
    "equal": ["inadequate", "unequal"],
    "focused": ["unfocused", "unfocussed"],
    "measure": "illimitable",
    "numerous": ["infinite", "innumerable", "innumerous", "multitudinous", "myriad", "uncounted", "unnumberable", "unnumbered", "unnumerable"],
    "quiet": ["anxious", "anxiousness", "cark", "disorder", "disquiet", "distract", "nervous", "perturb", "queasy", "trouble", "unease", "uneasiness", "uneasy", "unhinge", "unquiet"],
    "revealed": ["undisclosed", "unrevealed"],
    "specifically": "nonspecifically",
    "affected": ["alien", "alienate", "disaffect", "disaffected", "estrange", "ill-affected", "insensible", "malcontent", "rebellious", "unaffected", "unmoved", "untouched"],
    "aircraft": ["ack-ack", "ack-ack gun", "antiaircraft", "antiaircraft gun", "flack", "flak", "pom-pom"],
    "claimed": "unclaimed",
    "corporate": ["comprise", "contain", "discorporate", "disembodied", "incorporate", "incorporated", "integrate", "integrated", "merged", "unbodied", "unembodied", "unified"],
    "determined": ["indeterminate", "open", "undecided", "undetermined", "unresolved"],
    "extended": "unextended",
    "fault": ["immaculate", "impeccable"],
    "friendly": ["hostile", "inimical", "uncongenial", "unfriendly"],
    "lay": "inlay",
    "mixed": ["plain", "sheer", "uncompounded", "unmingled", "unmixed"],
    "properly": "improperly",
    "pure": ["impure", "unclean"],
    "reduced": "unreduced",
    "sat": ["antisatellite", "asat"],
    "secure": ["insecure", "unsafe"],
    "talent": "untalented",
    "tony": ["amyotonia", "atonia", "atonicity", "atony"],
    "blame": ["inculpable", "irreproachable", "unimpeachable"],
    "collected": ["uncollected", "ungathered"],
    "dying": "undying",
    "elected": ["nonelected", "nonelective"],
    "experienced": ["inexperienced", "inexperient"],
    "identified": ["unidentified", "unknown", "unnamed"],
    "inspired": ["sterile", "unimaginative", "uninspired", "uninventive"],
    "noticed": "unnoticed",
    "obvious": "unobvious",
    "worried": ["carefree", "unworried"],
    "charged": ["acquit", "assoil", "clear", "complete", "discharge", "discharged", "dismissed", "dispatch", "drop", "drop off", "eject", "empty", "exculpate", "exhaust", "exonerate", "expel", "fire", "fired", "free", "go off", "laid-off", "muster out", "pink-slipped", "put down", "release", "set down", "uncharged", "unload"],
    "typically": ["atypically", "untypically"],
    "usual": ["strange", "unusual"],
    "assembly": ["disassembly", "dismantlement", "dismantling"],
    "capable": ["incapable", "incompetent", "unequal to"],
    "essential": ["incidental", "inessential", "nonessential", "unessential"],
    "familiar": "unfamiliar",
    "guilty": ["clean-handed", "innocent"],
    "improved": "unimproved",
    "perfectly": ["amiss", "imperfectly"],
    "relevant": "irrelevant",
    "wing": ["amazing", "awe", "awe-inspiring", "awesome", "awful", "awing"],
    "bomb": ["a-bomb", "atom bomb", "atomic bomb", "fission bomb", "plutonium bomb"],
    "creative": "uncreative",
    "directed": ["adrift", "afloat", "undirected"],
    "affect": ["alien", "alienate", "disaffect", "estrange"],
    "appointed": ["defeated", "disappoint", "disappointed", "discomfited", "foiled", "frustrated", "let down", "thwarted"],
    "armed": ["disarm", "unarm", "unarmed"],
    "controlled": "uncontrolled",
    "corporation": ["incorporation", "internalisation", "internalization"],
    "explained": "unexplained",
    "motion": ["inactive", "static", "still"],
    "realized": ["unfulfilled", "unrealised", "unrealized"],
    "reasonable": ["excessive", "inordinate", "undue", "unreasonable"],
    "resolution": ["indecision", "indecisiveness", "irresoluteness", "irresolution"],
    "ryan": ["aryan", "indo-aryan", "indo-european"],
    "typical": ["antitypic", "antitypical", "atypical", "irregular", "untypical"],
    "dedicated": "undedicated",
    "favor": ["disadvantage", "disapproval", "disfavor", "disfavour", "dislike"],
    "load": ["discharge", "drop", "drop off", "offload", "put down", "set down", "unlade", "unload"],
    "possibility": ["impossibility", "impossible action", "impossibleness"],
    "random": "nonrandom",
    "trained": "untrained",
    "understood": "ununderstood",
    "accurate": "inaccurate",
    "competitive": ["noncompetitive", "uncompetitive"],
    "fruit": ["futile", "vain"],
    "parent": "unparented",
    "permanent": ["impermanent", "temporary"],
    "personally": "impersonally",
    "pleasure": "displeasure",
    "representative": ["nonrepresentative", "unrepresentative", "unsymbolic"],
    "tank": "antitank",
    "tend": ["designate", "destine", "dilate", "distend", "intend", "mean", "signify", "specify", "stand for", "think"],
    "button": "unbutton",
    "counter": ["discount house", "discount store", "discounter", "wholesale house"],
    "crown": "uncrowned",
    "defined": ["undefined", "vague"],
    "employment": "unemployment",
    "exclusive": ["unexclusive", "unrestricted"],
    "expert": ["amateur", "amateurish", "inexpert", "unskilled"],
    "frequently": "infrequently",
    "grace": ["attaint", "degrade", "demean", "discredit", "disgrace", "dishonor", "dishonour", "gauche", "ignominy", "put down", "shame", "take down", "ungraceful", "unpleasing", "unpolished"],
    "importance": ["humbleness", "lowliness", "obscureness", "unimportance"],
    "laid": ["inlaid", "inlay"],
    "personnel": "antipersonnel",
    "pregnant": "nonpregnant",
    "sleeping": ["unsleeping", "wide-awake"],
    "concert": ["confuse", "discomfit", "discompose", "disconcert", "flurry", "put off", "untune", "upset"],
    "declared": "undeclared",
    "earned": "unearned",
    "existence": ["nonentity", "nonexistence"],
    "expression": ["deadpan", "impassive", "poker-faced", "unexpressive"],
    "headed": "unheaded",
    "mate": ["con", "convict", "inmate", "inpatient", "yard bird", "yardbird"],
    "panel": ["empanel", "impanel"],
    "resistance": "nonresistance",
    "roof": "dispossessed",
    "shame": "unblushing",
    "checked": ["unbridled", "unchecked", "uncurbed", "ungoverned"],
    "constant": "inconstant",
    "doors": ["indoors", "inside"],
    "exciting": ["unexciting", "unstimulating"],
    "print": ["depression", "embossment", "form", "impress", "impression", "imprint"],
    "sight": ["brainstorm", "brainwave", "insight", "penetration", "perceptiveness", "perceptivity", "sixth sense", "unseeing"],
    "significantly": "insignificantly",
    "attractive": ["unattractive", "untempting"],
    "broad": ["abroad", "afield", "overseas"],
    "drawn": ["indrawn", "undrawn", "withdrawn"],
    "invited": "uninvited",
    "loud": ["aloud", "loudly", "out loud"],
    "motor": ["unmotorised", "unmotorized"],
    "officially": ["on the side", "unofficially"],
    "attached": ["free-swimming", "unattached", "uncommitted"],
    "breath": ["breathtaking", "dyspneal", "dyspneic", "dyspnoeal", "dyspnoeic", "inanimate"],
    "engaged": ["unengaged", "unpledged", "unpromised"],
    "expressed": ["unexpressed", "unsaid", "unspoken", "unstated", "unuttered", "unverbalised", "unverbalized", "unvoiced"],
    "presidential": "unpresidential",
    "recognized": ["unrecognised", "unrecognized"],
    "registered": "unregistered",
    "regularly": ["irregularly", "on an irregular basis"],
    "aim": ["adrift", "afloat", "drifting", "floating", "undirected", "vagabond", "vagrant"],
    "entitled": ["unentitled", "unqualified"],
    "exact": "inexact",
    "fed": "unfed",
    "injured": "uninjured",
    "lock": "unlock",
    "musical": ["nonmusical", "unmelodic", "unmelodious", "unmusical"],
    "opposed": "unopposed",
    "organized": ["disorganise", "disorganised", "disorganize", "disorganized", "nonunionised", "nonunionized", "unorganised", "unorganized"],
    "protected": "unprotected",
    "tie": ["loosen", "unbrace", "undo", "unlace", "untie"],
    "valuable": "invaluable",
    "wise": ["inexpedient", "unwise"],
    "aged": ["minor", "nonaged", "unaged", "underage"],
    "approval": ["disapproval", "disfavor", "disfavour", "dislike"],
    "equivalent": "nonequivalent",
    "fairly": ["below the belt", "unfairly"],
    "founded": ["idle", "unfounded", "unwarranted", "wild"],
    "marked": ["overlooked", "unmarked", "unnoted"],
    "rid": ["arid", "desiccate", "desiccated"],
    "visual": "nonvisual",
    "wheel": "awheel",
    "appointment": ["dashing hopes", "disappointment", "letdown"],
    "colour": ["color", "discolor", "discolour"],
    "effectively": ["ineffectively", "inefficaciously"],
    "formation": ["data", "entropy", "info", "information", "selective information"],
    "jury": ["accidental injury", "combat injury", "harm", "hurt", "injury", "trauma", "wound"],
    "promised": ["unengaged", "unpledged", "unpromised"],
    "sought": ["undesired", "unsought"],
    "studied": ["uncontrived", "unstudied"],
    "tone": ["aby", "abye", "atone", "cantillate", "chant", "expiate", "intonate", "intone", "repent"],
    "consistent": ["discrepant", "inconsistent"],
    "naturally": ["artificially", "by artificial means", "unnaturally"],
    "necessarily": "unnecessarily",
    "practical": ["airy", "impractical", "laputan", "visionary", "windy"],
    "proved": ["ameliorate", "amend", "better", "improve", "improved", "meliorate", "unproved", "unproven"],
    "regardless": ["disregarding", "irrespective", "no matter"],
    "rush": ["inpour", "inpouring", "inrush"],
    "stable": ["fluid", "mentally ill", "precarious", "unsound", "unstable"],
    "tested": ["unseasoned", "untested", "untried", "young"],
    "attended": ["neglected", "unattended"],
    "chart": ["uncharted", "unmapped"],
    "complicated": ["elementary", "simple", "uncomplicated", "unproblematic", "unsophisticated"],
    "confused": ["unbaffled", "unconfused"],
    "divided": ["exclusive", "single", "undivided"],
    "gate": "agate",
    "impressive": "unimpressive",
    "loving": "unloving",
    "mount": ["add up", "amount", "amount of money", "come", "dismount", "get down", "get off", "light", "measure", "number", "quantity", "sum", "sum of money", "total", "unhorse"],
    "tied": ["loosen", "unbrace", "unchained", "undo", "unfastened", "unfettered", "unlace", "unlaced", "unshackled", "untie", "untied"],
    "awful": "disrespectful",
    "belief": ["disbelief", "incredulity", "mental rejection", "skepticism", "unbelief"],
    "bound": ["abound", "bristle", "burst", "inbound", "inward", "unbind", "unbound", "unbounded"],
    "cloud": "unclouded",
    "establish": "disestablish",
    "loose": ["free", "liberate", "release", "unloose", "unloosen"],
    "moral": ["base", "immoral"],
    "offensive": ["euphemistic", "inoffensive", "unoffending"],
    "pointed": "unpointed",
    "qualified": ["disqualified", "disqualify", "incompetent", "indispose", "unentitled", "unfit", "unqualified"],
    "sensitive": ["insensitive", "nonsensitive", "unrestricted"],
    "violent": ["nonviolent", "unbloody"],
    "wash": ["afloat", "awash", "flooded", "inundated", "overflowing"],
    "acid": ["alkaliser", "alkalizer", "antacid", "antiacid", "gastric antacid"],
    "covering": ["baring", "bring out", "denudation", "discovery", "expose", "find", "husking", "reveal", "stripping", "uncover", "uncovering", "unveil"],
    "curious": "incurious",
    "formal": ["cozy", "informal", "intimate", "loose"],
    "informed": "uninformed",
    "scheduled": "unscheduled",
    "spoken": ["mute", "unexpressed", "unsaid", "unspoken", "unstated", "unuttered", "unverbalised", "unverbalized", "unvoiced"],
    "successfully": "unsuccessfully",
    "awareness": ["unawareness", "unknowingness"],
    "fiction": ["nonfiction", "nonfictional prose"],
    "happiness": ["sadness", "unhappiness"],
    "passion": ["dispassion", "dispassionateness", "dryness"],
    "pleased": ["displease", "displeased"],
    "settled": ["changeable", "enervate", "faze", "uncertain", "unnerve", "unsettle", "unsettled"],
    "helpful": ["incapacitated", "lost", "unhelpful"],
    "locked": ["unbarred", "unbolted", "unlatched", "unlock", "unlocked", "unsecured"],
    "romantic": "unromantic",
    "wire": ["radio", "radio receiver", "radio set", "radiocommunication", "receiving set", "tuner", "unwire"],
    "worker": "nonworker",
    "belt": ["unbelt", "unbelted"],
    "dressed": ["discase", "disinvest", "disrobe", "divest", "peel", "strip", "strip down", "unappareled", "unattired", "uncase", "unclad", "unclothe", "undress", "undressed", "ungarbed", "ungarmented"],
    "efficient": ["ineffective", "inefficient"],
    "employed": ["unemployed", "unemployed people"],
    "establishment": "disestablishment",
    "flower": "nonflowering",
    "racist": ["color-blind", "colour-blind", "nonracist"],
    "sexy": ["neuter", "unsexy"],
    "solve": ["break up", "dethaw", "disband", "dismiss", "dissolve", "fade away", "fade out", "melt", "resolve", "thaw", "unfreeze", "unthaw"],
    "comfort": ["discomfort", "irritation", "soreness", "uncomfortableness"],
    "dies": "undies",
    "dramatic": "undramatic",
    "dust": ["adust", "baked", "parched", "scorched", "sunbaked"],
    "memorial": "immemorial",
    "repair": "disrepair",
    "root": "vagabond",
    "buried": "unburied",
    "butter": "abutter",
    "convinced": "unconvinced",
    "decent": ["indecent", "indecorous", "unbecoming", "uncomely", "unseemly", "untoward"],
    "marry": "inmarry",
    "organic": "inorganic",
    "smooth": ["rough", "unsmooth"],
    "string": "unstring",
    "assigned": "unassigned",
    "associate": ["disassociate", "disjoint", "dissociate", "disunite", "divorce"],
    "bye": ["aby", "abye", "atone", "expiate"],
    "citizen": ["alien", "foreigner", "noncitizen", "outlander"],
    "damaged": "undamaged",
    "equally": ["unequally", "unevenly"],
    "figured": ["blemish", "deface", "disfigure", "disfigured"],
    "fitness": ["inability", "softness", "unfitness"],
    "observed": ["unobserved", "unseen"],
    "visible": ["inconspicuous", "invisible", "unseeable"],
    "commonly": "uncommonly",
    "connect": ["disconnect", "disconnection", "gulf", "unplug"],
    "efficiency": "inefficiency",
    "pace": ["apace", "chop-chop", "quickly", "rapidly", "speedily"],
    "pope": "antipope",
    "possession": ["dispossession", "eviction", "exorcism", "legal ouster"],
    "resident": "nonresident",
    "shaped": ["unshaped", "unshapen"],
    "suitable": ["inapplicable", "undesirable", "unsuitable"],
    "valid": ["disable", "handicap", "incapacitate", "invalid", "shut-in"],
    "anna": "inanna",
    "honour": ["assault", "attaint", "disgrace", "dishonor", "dishonour", "outrage", "rape", "ravish", "shame", "violate"],
    "hook": "unhook",
    "log": ["antilog", "antilogarithm"],
    "settle": ["enervate", "faze", "unnerve", "unsettle"],
    "sin": ["asin", "asvina", "impeccant", "innocent"],
    "spell": "unspell",
    "tongue": ["mute", "unspoken"],
    "ward": ["accolade", "award", "awarding", "grant", "honor", "honour", "inbound", "inward", "inwards", "laurels", "present", "prize"],
    "achievement": ["nonaccomplishment", "nonachievement"],
    "automatic": "hand-operated",
    "comprehensive": ["incomprehensive", "noncomprehensive"],
    "engage": ["disengage", "free", "withdraw"],
    "frequency": ["infrequency", "rareness", "rarity"],
    "gene": ["agene", "nitrogen trichloride"],
    "juice": "dry",
    "logic": ["illogic", "illogicality", "illogicalness", "inconsequence"],
    "objective": ["abstract", "abstractionist", "nonfigurative", "nonobjective", "unobjective", "unverifiable"],
    "organisation": ["disarrangement", "disorganisation", "disorganization"],
    "regard": ["brush aside", "brush off", "cut", "discount", "dismiss", "disregard", "disregarding", "ignore", "irrespective", "neglect", "no matter", "push aside", "snub"],
    "tube": "tubeless tire",
    "breast": ["abreast", "au courant", "au fait", "up on"],
    "cant": ["descant", "discant"],
    "corruption": ["incorruption", "incorruptness"],
    "crossed": ["uncross", "uncrossed"],
    "fancy": ["babyhood", "early childhood", "infancy"],
    "grateful": ["ungrateful", "unthankful"],
    "knock": ["antiknock", "antiknocking"],
    "painted": "unpainted",
    "ranked": ["ungraded", "unordered", "unranked"],
    "tear": "dry-eyed",
    "ate": ["irate", "ireful"],
    "ease": ["disease", "disquiet", "malaise", "unease", "uneasiness"],
    "impressed": "unimpressed",
    "progressive": ["fusty", "nonprogressive", "standpat", "unprogressive"],
    "reader": ["illiterate", "illiterate person", "nonreader"],
    "tail": "anurous",
    "alert": ["unalert", "unvigilant", "unwatchful"],
    "constitutional": "unconstitutional",
    "gen": "antigen",
    "infection": "disinfection",
    "mechanical": ["nonmechanical", "unmechanical"],
    "participation": "nonparticipation",
    "proven": ["unproved", "unproven"],
    "requested": "unrequested",
    "residential": "nonresidential",
    "satellite": ["antisatellite", "asat"],
    "shore": ["ashore", "inshore", "onshore", "seaward", "shoreward"],
    "substantial": ["insubstantial", "jejune", "unreal", "unsubstantial"],
    "uniform": ["inhomogeneous", "nonuniform"],
    "aggressive": ["nonaggressive", "unaggressive"],
    "answered": ["unanswered", "unreciprocated", "unrequited"],
    "apparent": "unapparent",
    "courage": ["admonish", "deter", "discourage", "monish", "warn"],
    "frozen": ["dethaw", "dissolve", "free", "melt", "release", "thaw", "unblock", "unfreeze", "unfrozen", "unthaw"],
    "humanity": ["atrocity", "inhumaneness", "inhumanity"],
    "invest": ["disinvest", "divest", "strip", "undress"],
    "occupied": ["unoccupied", "untenanted"],
    "painful": ["pain-free", "unpainful"],
    "pound": ["attach", "confiscate", "impound", "seize", "sequester"],
    "sufficient": ["deficient", "insufficient"],
    "wounded": "unwounded",
    "arranged": ["disarrange", "disarranged"],
    "distributed": "undistributed",
    "dynamic": ["adynamic", "asthenic", "debilitated", "enervated", "undynamic"],
    "edited": "unedited",
    "engagement": ["detachment", "disengagement", "fallback", "nonparticipation", "pullout"],
    "favour": ["disadvantage", "disapproval", "disfavor", "disfavour", "dislike"],
    "literary": ["nonliterary", "unliterary"],
    "mask": ["uncloak", "unmask"],
    "praise": ["disparagement", "dispraise"],
    "sean": "asean",
    "slave": "free-soil",
    "stability": ["imbalance", "instability", "unbalance", "unstableness"],
    "steady": ["unfirm", "unsteady"],
    "enable": ["disable", "disenable", "incapacitate"],
    "equity": ["inequity", "unfairness"],
    "failing": ["foolproof", "unfailing", "unflagging"],
    "intellectual": ["lowbrow", "nonintellectual", "philistine"],
    "involvement": "nonparticipation",
    "racial": "nonracial",
    "seal": "unseal",
    "stem": "acaulescent",
    "talented": "untalented",
    "touched": ["unaffected", "uninfluenced", "unmoved", "unswayed", "untasted", "untouched"],
    "dated": "undated",
    "derived": "underived",
    "distinct": "indistinct",
    "educated": "uneducated",
    "eligible": "ineligible",
    "franchise": ["disenfranchise", "disfranchise"],
    "funded": "unfunded",
    "guaranteed": ["unguaranteed", "unsecured"],
    "integrated": ["nonintegrated", "segregated", "unintegrated"],
    "intelligent": ["stupid", "unintelligent"],
    "regarded": ["brush aside", "brush off", "cut", "discount", "dismiss", "disregard", "disregarded", "forgotten", "ignore", "neglect", "push aside", "snub"],
    "reliable": ["treacherous", "undependable", "unreliable"],
    "remarkable": ["everyday", "mundane", "quotidian", "routine", "unremarkable", "workaday"],
    "sole": ["innersole", "insole"],
    "ton": ["aten", "aton"],
    "worthy": ["despicable", "slimy", "ugly", "undeserving", "unworthy", "vile", "wretched"],
    "bloody": ["ashen", "blanched", "exsanguine", "exsanguinous", "livid", "nonviolent", "unbloody", "white"],
    "consideration": ["inconsiderateness", "inconsideration", "thoughtlessness"],
    "crucial": ["noncritical", "noncrucial"],
    "dependent": ["autonomous", "fencesitter", "free lance", "free-lance", "freelance", "freelancer", "independent", "main", "mugwump", "self-employed person", "self-governing", "sovereign"],
    "equipped": "unequipped",
    "hoped": ["unhoped", "unhoped-for", "unthought", "unthought-of"],
    "involve": ["disembroil", "disentangle", "disinvolve"],
    "las": ["ala", "alas", "regrettably", "unfortunately", "unluckily"],
    "mature": ["green", "immature", "unfledged", "unripe", "unripened", "young"],
    "peaceful": "unpeaceful",
    "pin": "unpin",
    "printing": ["form", "impress", "imprint", "imprinting"],
    "satisfied": ["disgruntled", "dissatisfied", "dissatisfy", "ungratified", "unsated", "unsatiated", "unsatisfied"],
    "slip": "nonslip",
    "surprising": "unsurprising",
    "acceptable": ["impossible", "insufferable", "unacceptable", "unaccepted", "unsufferable"],
    "composed": ["discomfit", "discompose", "discomposed", "disconcert", "untune", "upset"],
    "frequent": "infrequent",
    "gathered": ["uncollected", "ungathered"],
    "moderate": "immoderate",
    "parallel": ["antiparallel", "in series", "nonparallel", "serial", "unparallel"],
    "quest": "inquest",
    "radiation": ["actinotherapy", "beam", "beam of light", "irradiation", "light beam", "radiation therapy", "radiotherapy", "ray", "ray of light", "shaft", "shaft of light"],
    "sized": "unsized",
    "stroke": "instroke",
    "tune": ["discomfit", "discompose", "disconcert", "unmelodious", "untune", "untuneful", "upset"],
    "utility": ["inutility", "unusefulness", "uselessness"],
    "addressed": "unaddressed",
    "backed": ["single-handed", "unassisted", "unbacked"],
    "classical": "nonclassical",
    "classified": "unclassified",
    "clip": "unclip",
    "equality": "inequality",
    "intervention": ["noninterference", "nonintervention"],
    "waited": ["anticipated", "await", "awaited", "expect", "hoped-for", "look", "wait"],
    "accompanied": ["alone", "solo", "unaccompanied"],
    "arrangement": ["disarrangement", "disorganisation", "disorganization"],
    "considerable": "inconsiderable",
    "conventional": ["improper", "unconventional", "unlawful"],
    "gathering": ["appeal", "collection", "ingathering", "solicitation"],
    "loaded": ["discharge", "drop", "drop off", "offload", "put down", "set down", "unlade", "unload", "unloaded"],
    "measured": ["immeasurable", "immensurable", "unmeasurable", "unmeasured"],
    "mercy": "unmerciful",
    "powered": "unpowered",
    "screw": "unscrew",
    "tribute": ["administer", "allot", "broadcast", "circularise", "circularize", "circulate", "deal", "deal out", "diffuse", "dish out", "dispense", "disperse", "disseminate", "distribute", "dole out", "give out", "hand out", "lot", "mete out", "parcel out", "pass around", "pass on", "pass out", "propagate", "shell out", "spread", "stagger"],
    "venue": ["avenue", "boulevard"],
    "accuracy": "inaccuracy",
    "consistently": "inconsistently",
    "functional": ["malfunctioning", "nonfunctional", "unfunctional"],
    "habit": ["dwell", "inhabit", "live", "populate"],
    "modified": "unmodified",
    "popularity": "unpopularity",
    "shoe": ["barefoot", "barefooted"],
    "toxic": ["antitoxic", "atoxic", "nonpoisonous", "nontoxic"],
    "assuming": ["retiring", "unassuming"],
    "blessed": "unblessed",
    "burden": ["disburden", "unburden", "unburdened"],
    "certified": "uncertified",
    "controversial": ["noncontroversial", "uncontroversial"],
    "differently": "indifferently",
    "discipline": ["indiscipline", "undiscipline"],
    "graphic": "agraphic",
    "secured": ["unbarred", "unbolted", "unguaranteed", "unlatched", "unlocked", "unsecured"],
    "bearing": "nonbearing",
    "com": ["enlisted officer", "noncom", "noncommissioned officer"],
    "integration": ["annihilation", "decay", "decomposition", "disintegration", "dissolution", "radioactive decay"],
    "legitimate": ["bastard", "by-blow", "illegitimate", "illegitimate child", "illicit", "love child", "outlaw", "outlawed", "unlawful", "whoreson"],
    "pleasant": "unpleasant",
    "productive": ["nonproductive", "unproductive"],
    "tension": ["connotation", "dilatation", "distension", "distention", "intension"],
    "twist": "untwist",
    "unity": "disunity",
    "beaten": ["unbeaten", "unconquered", "unvanquished"],
    "bitter": "unbitter",
    "continuous": ["discontinuous", "noncontinuous"],
    "converted": ["unconverted", "unpersuaded"],
    "correctly": ["falsely", "incorrectly", "wrong", "wrongly"],
    "forming": ["inform", "informing", "making known", "ratting"],
    "ken": ["aachen", "aix-la-chapelle", "aken"],
    "legally": ["illegally", "illicitly"],
    "nasa": ["anasa", "genus anasa"],
    "operational": ["inactive", "nonoperational"],
    "vulnerable": "invulnerable",
    "caring": ["detached", "unaffectionate", "uncaring", "unthinking"],
    "cleared": "uncleared",
    "distinguished": ["insignificant", "undistinguished"],
    "generous": ["meanspirited", "stingy", "ungenerous"],
    "incorporated": "unincorporated",
    "influenced": ["uninfluenced", "unswayed", "untouched"],
    "loyal": ["disloyal", "unpatriotic"],
    "patch": ["bump off", "communique", "complete", "despatch", "discharge", "dispatch", "expedition", "expeditiousness", "hit", "murder", "off", "polish off", "remove", "send off", "shipment", "slay"],
    "patience": ["impatience", "restlessness"],
    "pollution": "antipollution",
    "precisely": ["imprecisely", "inexactly"],
    "resist": ["irresistible", "supine", "unresisting"],
    "wrap": ["break", "bring out", "disclose", "discover", "divulge", "expose", "give away", "let on", "let out", "reveal", "undo", "unwrap"],
    "boot": ["futile", "vain"],
    "colored": ["unbleached", "uncolored", "uncoloured", "undyed"],
    "corn": "acorn",
    "humor": "unhumorous",
    "lit": ["unilluminated", "unlighted", "unlit"],
    "nerve": ["cool", "coolheaded", "enervate", "faze", "feeble", "unnerve", "unsettle"],
    "partially": "impartially",
    "poster": ["fake", "faker", "fraud", "imposter", "impostor", "pretender", "pseud", "pseudo", "role player", "sham", "shammer"],
    "qualify": ["disqualify", "indispose", "unfit"],
    "ram": "aram",
    "respective": ["disregarding", "irrespective", "no matter"],
    "restricted": ["nonsensitive", "unexclusive", "unrestricted"],
};
